### ISSUE TITLE
Adding this zip from Victoria, Australia causes a hang

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#11]
from @rmglennon on https://github.com/transitland/feed-registry/issues/121

> This feed from Victoria, Australia has a few issues with it, including subfolders, a zip that uses pkzip format, and being behind a checkbox. 
> 
> http://data.ptv.vic.gov.au/downloads/gtfs.zip
> 
> Home page for the operator's feed: https://www.data.vic.gov.au/data/dataset/ptv-timetable-and-geographic-information-2015-gtfs
> 
> Attempting to add it causes a hang when parsing the operators.

Will need support for nested zip files: https://github.com/transitland/transitland-datastore/issues/316

In the meantime, we'll return better error messages: https://github.com/transitland/transitland-datastore/issues/317

**Comment by rmglennon** [comment]
Looking at this transit page again (was testing our error catchers), all the comments are asking when the feed will be in Google Maps, with others talking about how the feed doesn't comply with the spec and will never be added....and how the feed is now out of date.

https://www.data.vic.gov.au/data/dataset/ptv-timetable-and-geographic-information-2015-gtfs

**Comment by drewda** [comment]
This should be possible, now that Datastore supports nested ZIP files.

I'm working through the nested feeds on my local machine, using:

`bundle exec rake csv_to_feeds[adelaide_gtfs_feeds.csv,url]`

[adelaide_gtfs_feeds.csv.txt](https://github.com/transitland/transitland/files/309723/adelaide_gtfs_feeds.csv.txt)

Still getting some issues with individual subfeeds (like `#5`).

**Comment by drewda** [comment]
Public Transport Victoria has been available in Feed Registry and Datastore API for a good while now: https://transit.land/feed-registry/operators/o-r1-ptv
