### ISSUE TITLE
How to reject a contribution that modifies an existing feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#110]
This contributor submitted a feed for Douai, France, which I accepted. The next day they submitted a modification to that feed, which would change the `shortName` and URL to a transit riders union. 

I want to "reject" this changeset. 

Currently there are two methods at my disposal to reject it. 

1. Delete the payload, apply the changeset. This sends the contributor an email saying we've accepted their submission. Obviously I would delete the payload before accepting the changeset so that the contributor's modifications are not applied. 
2. Edit and delete the changeset.

Neither method explains the problem to the contributor.

**Comment by stevevance** [comment]
If it's a new person submitting an existing feed, or a change to an existing feed, then I will always apply the changeset so they get the notification email that thanks them for their submission. 

I may edit or delete the payload as appropriate.

**Comment by drewda** [comment]
@stevevance sounds like a fine approach for the time being.

Related, for the future: https://github.com/transitland/transitland/issues/24
