### ISSUE TITLE
The Blue & Gold Fleet feed isn't for transit

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#111]
Mike Migurski [submitted a feed](https://transit.land/dispatcher/changesets/2181) for the Blue & Gold Fleet, which is a tourist ferry. Since it's not transit I don't think it should be included in Transitland.

**Comment by drewda** [comment]
@stevevance agreed.

Commuter ferries and water taxis are definitely useful additions to Transitland--they provide access to land-based destinations--but tourist boat rides are likely not useful coverage. Blue & Gold Fleet does operate commuter ferries (http://m.blueandgoldfleet.com/ferry-routes-schedules/), but this feed appears to only include the Rocket Boat ride.

And much as we may like the submitter, a feed hosted on a personal domain doesn't fit Transitland's current emphasis on submissions from authoritative agency or civic group sources.

//cc @migurski

**Comment by migurski** [comment]
No love for the Rocketboat.

**Comment by stevevance** [comment]
@migurski Have you ridden the Rocket Boat?

**Comment by migurski** [comment]
Absolutely — the GPS trace in this feed is me.
