### ISSUE TITLE
Duplicate operators in Longueuil, Ontario, Canada

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#113]
It appears the only difference is that one of the operators' `onestopId` has the `é` character, and the same character was stripped out of the other operator's `onestopId`. 

1. `o-f25f-rseaudetransportdelongueuil` - [Feed Registry](https://transit.land/feed-registry/operators/o-f25f-rseaudetransportdelongueuil)
2. `o-f25f-réseaudetransportdelongueuil` - [Feed Registry](https://transit.land/feed-registry/operators/o-f25f-réseaudetransportdelongueuil)

I propose deleting the first operator, but since these are both imported at level 4, I wonder if there's any issues with deleting a `onestopId` that may have been around for a while (like, are any users dependent on this operator?).

**Comment by drewda** [comment]
@stevevance what a slight difference!

@irees can you investigate and see if this is as simple as deleting the first operator, or requires manually pruning back some other duplicate records like stops/routes?

**Comment by irees** [comment]
@drewda @stevevance 

All of the imported stops, routes, etc., are associated with `o-f25f-rseaudetransportdelongueuil` (without é). So, let's keep that one and delete `o-f25f-réseaudetransportdelongueuil`, which isn't referenced by any stops, routes.

If we want the é in the onestop_id, I can manually edit it via console after the duplicate is removed.

## o-f25f-réseaudetransportdelongueuil
http://transit.land/api/v1/stops?served_by=o-f25f-r%C3%A9seaudetransportdelongueuil&per_page=1&total=true
http://transit.land/api/v1/routes?operated_by=o-f25f-r%C3%A9seaudetransportdelongueuil&per_page=1&total=true

## o-f25f-rseaudetransportdelongueuil:
http://transit.land/api/v1/routes?operated_by=o-f25f-rseaudetransportdelongueuil&per_page=1&total=true
http://transit.land/api/v1/stops?served_by=o-f25f-rseaudetransportdelongueuil&per_page=1&total=true

**Comment by drewda** [comment]
@irees sounds good. Also, what do the `OperatorInFeed` records look like? Same `gtfs_agency_id`?

**Comment by irees** [comment]
@drewda 

This OperatorsInFeed will need to be removed:

http://transit.land/api/v1/feeds/f-f25f-rseaudetransportdelongueuil
```gtfs_agency_id: "RTL",
operator_onestop_id: "o-f25f-réseaudetransportdelongueuil",```

Also -- I need to add a uniqueness constraint on `gtfs_agency_id`.

**Comment by stevevance** [comment]
So, I will apply this changeset to destroy the operator with the `é` that has no associated stops and routes, and then apply @irees's changeset. 

````
{
    "changes": [{
        "action": "destroy",
        "operator": {
            "onestopId": "o-f25f-réseaudetransportdelongueuil"
        }
    }]
}
````

**Comment by drewda** [comment]
@stevevance and @irees are there any open tasks remaining on these operator records?

@irees let's talk about a uniqueness constraint on `gtfs_agency_id` separately. That likely interacts with https://github.com/transitland/transitland-datastore/issues/735

**Comment by drewda** [comment]
@irees will investigate on the console and follow up on whether this needs to be resolved manually or represents a bug in the changeset mechanisms.

**Comment by irees** [comment]
After some cleanup (https://github.com/transitland/transitland-datastore/issues/797) I think this ticket can be closed. The duplicate Operator was removed.

**Comment by drewda** [comment]
Closing this issue, since it sounds like all data-related clean-up has now been completed by @stevevance and @irees.

The code-related issues that this surfaced will happen separately on https://github.com/transitland/transitland-datastore/issues/797
