### ISSUE TITLE
List of various European feeds: Netherlands, Germany, Belgium, France, Switzerland

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#116]
A user submitted this list of European feeds by email. See support # 906 and 904.
- [ ] The Netherlands

In The Netherlands, they have aggregated the original 
feeds into a whole set of national gtfs feeds. Even ferry schedules are 
there. I think I remember I had issues uploading those using the form, because 
its such a big set, so here it is by email: http://gtfs.ovapi.nl/
- [ ] German Railways (DB)

http://patrickbrosi.de/en/projects/dbgtfs/

This is the official proprietary API page: 
http://data.deutschebahn.com/dataset/api-fahrplan

and this is the script to turn it into gtfs 
https://github.com/fredlockheed/db-fv-gtfs
- [x] More Belgian feeds

Also Flemish, Walone & Brussels busses 
https://hello.irail.be/gtfs/
- [x] French Railways (SNCF)

Documentation for the (realtime) API (which is not free) 
https://data.sncf.com/api/en/documentation

GTFS downloads: 
https://ressources.data.sncf.com/explore/?sort=modified&refine.keyword=GTFS

License for the GTFS files: 
https://data.sncf.com/licence 
If you would need help in translating meaning of certain datasets, of 
find your way around the site, I can try my best. I cant translate the 
license, its a legal document.
- [ ] Switzerland

I found switzerland, too: http://gtfs.geops.ch/

**Comment by drewda** [comment]
Thanks, @rmglennon!

The **Dutch** and **Swiss** feeds are ones that we've tested but not yet added to the production servers. Both depend on import performance improvements that have been happening slowly but steadily. Related: https://github.com/transitland/transitland/issues/27

The **German DB** API script and GTFS dumps are compelling but unproven. Perhaps in the future, we'll consider running that API script as a background job on the Transitland stack. But to depend on a third-party script that is being run by a different third-party sounds too complex. (These do look like fabulous experiments by thoughtful developers--my hesitancy specifically concerns putting this scraping process in production use on the Transitland stack.)

**Belgian** feeds: tagging @stevevance in case he wants to investigate that list.

@stevevance is handling **French SNCF** trains under #109

**Comment by stevevance** [comment]
SNCF is completed. 

The Switzerland feed in [changeset 673](https://transit.land/dispatcher/changesets/673) has 409 operators. That's insane, and that's going to take a very long time for me, or anyone, to edit. 

@drewda A lot of the operators are missing `state` and `metro` values. If the feed was resubmitted to the Feed Registry, would those values be extracted from the feed?

**Comment by stevevance** [comment]
The Netherlands feed is enqueued for import, more details in #27 
The Belgian feed is imported.
I have started working through the Swiss feed.

**Comment by drewda** [comment]
Closing this, since it looks like all of the feeds that are simple to add and import have been completed, and notes on more complex feeds are under individual issues.
