### ISSUE TITLE
Washington Metro Route RSP off road

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland#117]
[Washington Metro (o-dqc-met)](https://transit.land/feed-registry/operators/o-dqc-met) bus route: r-dqcj-96.

Bus route traverses through park.

**Comment by stevevance** [comment]
How did you figure that out?

**Comment by doublestranded** [comment]
Chance find by @meghanhade. I'm assigning this to myself for now so I can use it test out the new route editing functionality.

**Comment by stevevance** [comment]
Do you have an update on this?

**Comment by drewda** [comment]
Closing this, since we don't right now have time to manually edit and improve route geometries in feeds. In the future, we can make the route editing tools more accessible to others who are interested in making these types of edits.
