### ISSUE TITLE
Sweden

### ISSUE THREAD

**Issue by batje** [transitland/transitland#119]
https://www.trafiklab.se/api/gtfs-sverige-2

The .zip file is not available without an API key, but the file is available under the  Creative Commons Attribution license, which might be compatible with transitland.

**Comment by stevevance** [comment]
@batje Is this for all of Sweden or a particular region?

**Comment by batje** [comment]
According to Google Translate, it seems to be. Also trafiklab looks to be a sub-project of http://www.samtrafiken.se/ which is the collective public transport organisation in Sweden, powering the generic site http://reseplanerare.resrobot.se

**Comment by stevevance** [comment]
It's simple to obtain an API key, but that's not our procedure. 

I think we could reach out to Trafiklab and ask them for an API key without having to "create a project" on their website. 

[Documentation on API keys](https://www.trafiklab.se/api/dokumentation/nycklar)

konto@trafiklab.se

**Comment by drewda** [comment]
This is now in the Feed Registry (using an API key): http://transit.land/feed-registry/?country=SE

Queued up for feed import.
