### ISSUE TITLE
Handling "Trenitalia" correctly

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#122]
"Trenitalia" is a brand name of intercity trains in Italy. The brand name is owned by the federal railways company. 

People have submitted multiple feeds – like [Tuscany](https://transit.land/dispatcher/changesets/2312) – with the name Trenitalia and I've accepted none of them so far because it would be preferable to have a single feed with all of the regions. 

If a single feed doesn't exist, then care must be taken to create a `onestopId` for the "Trenitalia" operator with a geohash that covers all of Italy. Any feeds for Trenitalia routes would reference this as their operator. 
- [x] Look for a single Trenitalia feed - **not found**
- [x] Update the operator service area GeoJSON on [o-s-trenitalia](https://transit.land/feed-registry/operators/o-s-trenitalia)

_List of Trenitalia-related feeds_
- [x] [Austria-Bolzano-Verona](https://transit.land/dispatcher/changesets/2340)
- [x] [Austria-Trento-Bassano del Grappa](https://transit.land/dispatcher/changesets/2339)
- [x] [Marche](https://transit.land/dispatcher/changesets/2336) - this feed includes more operators than just Trenitalia. 
- [x] [Tuscany](https://transit.land/dispatcher/changesets/2312)
- [x] [Sardinia](https://transit.land/dispatcher/changesets/2415)

_Notes_
The `f-u0j-torino` feed for the four Torino/Turin operators also includes in its `agency.txt` file an operator for FS/Trenitalia (FS is Ferrovie dello Stato, the government-owned national railway company), but it doesn't include any "FS" routes. "FS", however, is an agency name used in the _Marche_ feed above.

**Comment by drewda** [comment]
@stevevance sounds like a good option to create an operator record with both a Onestop ID and a rough geometry to cover all of Italy. In terms of checking the geohash in the Onestop ID, we often use this tool for reference http://mapzen.github.io/leaflet-spatial-prefix-tree/ (just be sure to toggle to the geohash mode using the button in the upper right)

**Comment by stevevance** [comment]
I have a revised proposal to create two operators with the name "Trenitalia". The second operator, however, would be a combined name: "Trenitalia/ÖBB" because the Austrian national operator ÖBB (Ostereichische Bundesbahnen) co-operates the inter-country trains. 

*Feeds under "Trenitalia"*
-Marche

**Comment by irees** [comment]
Applying changeset twice on two nodes caused duplicate `onestop_id`s, see: https://github.com/transitland/transitland-datastore/issues/779

**Comment by stevevance** [comment]
Ah. 

@irees I hit the "apply changeset" button multiple times on a bunch of changesets. Might I have created more problems? I'd look for any changesets made since 3 PM CST.

**Comment by stevevance** [comment]
The operator service area for `o-s-trenitalia` needs to be reset. Is there a way to do that automatically, by looking at all the feeds that make up this network operator?

**Comment by drewda** [comment]
@stevevance as feeds are imported, the stops they add will automatically increase the operator's service area during the import process. If necessary, we can trigger a manual recompute of any operator's service area at any later point, too.
