### ISSUE TITLE
Chennai feed is having an import problem

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#131]
[f-tf34-metropolitantransportcorporation](https://transit.land/dispatcher/feeds/f-tf34-metropolitantransportcorporation) and [the feed URL](https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/blob/master/mtc_chennai.zip?raw=true).
This happened after I changed the feed URL to one hosted on our repo. 

The error log starts with "GTFS::InvalidSourceException"

**Comment by stevevance** [comment]
I was going through feeds that still haven't been imported and this one came up again. Our new Dispatcher issues system [also caught it](https://transit.land/dispatcher/issues/feed-fetch/197458):

`GTFS feed does not contain the required files, or there was an unknown problem with fetching.`

It's hard to know if this feed is even real/acceptable anymore because the calendar information was last updated in 2010.

**Comment by stevevance** [comment]
This one was imported successfully but is outdated.

**Comment by drewda** [comment]
It's still of interest to have operator, routes, and stops. But we should probably clear out the schedule data and set this back down to level 1

**Comment by stevevance** [comment]
Changed to level 1.
