### ISSUE TITLE
Ireland

### ISSUE THREAD

**Issue by batje** [transitland/transitland#137]
I found a list of Irish GTFS feeds. I added Dublin Bus using the webform. If all is ok, there are about 67 more to add 
source:
http://www.transportforireland.ie/transitData/PT_Data.html

Portal:
https://www.europeandataportal.eu/data/en/dataset?license_id=cc-by&res_format=gtfs&organization=data-gov-ie&groups=transport&page=4

**Comment by batje** [comment]
Dublin Bus was accepted, great. So I started from the top of the list. I got only 1 confirmation email and I got an error on the last page of the wizard when uploading the trains. Also, the trains seems to have the same operator 4 times. 
Note to self: Stopped at Bus Eireann for now, next up McGeehan.

**Comment by stevevance** [comment]
@batje I'm the one accepting your changes. Thank you for submitting them. 

"I got an error on the last page of the wizard when uploading the trains" -> Which feed URL gave you this problem?

**Comment by stevevance** [comment]
@drewda @irees One of the feeds that @batje graciously submitted is for the "Luas replacement bus", which is shuttle service during a major construction works on the Dublin light rail. I looked at the calendar to see if it was active, and the last service date was 31 July 2016. 

Should I import [that feed](https://transit.land/dispatcher/changesets/2439)?

**Comment by batje** [comment]
@stevevance Am going top to bottom through the GTFS files listed in the lower half of the page on http://www.transportforireland.ie/transitData/PT_Data.html 

The trains are in the 'Irish Rail' file: 
http://www.transportforireland.ie/transitData/google_transit_irishrail.zip I retried tonight and again, i get an error on the last (of 4) pages of the upload form.

Also, in my browser I can download http://www.transportforireland.ie/transitData/google_transit_ptkkenneally.zip but the upload form says it gets a 404. Maybe you can retry?

I finished all GTFS files on the page. Only the Irish Rail and PT Kenneally files have failed. 

That should cover Ireland, I guess.

**Comment by stevevance** [comment]
Thank you so much @batje for sending in the feeds for all of the different Irish bus operators. 
I have finished importing all of them are they are available in the [Feed Registry](https://transit.land/feed-registry/?country=Ireland). 

@irees is looking into the other feeds right now.

**Comment by batje** [comment]
you are welcome. Now, for the country I actually live in [#27] :-)

**Comment by irees** [comment]
The error in Irish rail (http://www.transportforireland.ie/transitData/google_transit_irishrail.zip ) is the same issue as with Finland; see https://github.com/transitland/transitland-datastore/issues/735

**Comment by drewda** [comment]
Closing this issue, since Irish rail has been imported.

More improvement happening on https://github.com/transitland/transitland/issues/206

**Comment by harringtonp** [comment]
I see it is closed but... do any of the Irish transport providers have a GTFS realtime feed associated with them ? I couldn't find any that do

**Comment by drewda** [comment]
Transitland doesn't yet track GTFS-RT feeds. (It's a future plan; see #77)

TransitFeeds.com does include GTFS-RT feeds: http://transitfeeds.com/search?q=gtfsrt However, I do not currently see any listed from Ireland.

**Comment by harringtonp** [comment]
Thanks guys, got on to transportforireland.ie with an enquiry. Not too hopeful of getting a response but if there is something will report back here
