### ISSUE TITLE
Duplicate feeds

### ISSUE THREAD

**Issue by irees** [transitland/transitland#139]
## Look into:

Marin
"f-9qbb-wwwmarintransitorg", "f-9qbb-marintransit"

Delaware First State?
"f-dr4-dartfirststatecom", "f-dr4-dartfirststate"

Pittburgh
"f-dppn-wwwportauthorityorg", "f-dppn-portauthorityofalleghenycounty"

Italy
"f-u0j-gruppotorinesetrasporti~gttservizioextraurbano~gruppotorin", "f-u0j-gruppotorinesetrasporti~gttservizioextraurbano~gttservizit"

CT Transit
"f-drkhr-wwwcttransitcom", "f-dr79-wwwcttransitcom", "f-drkh-wwwcttransitcom", "f-drk-wwwcttransitcom", "f-drk5-cttransit~newhaven", "f-drk-cttransit~hartford"

Maybe duplicate:
"f-u0p-trentinotrasportieserciziospa", "f-u0pv-ttesercizio"

Ian: Rename to better represent area:
"f-r7h-translinkcomau", "f-r7hx-translinkcomau", "f-rhzx-translink"

Ian: Los Angeles Combined/Bus/Rail Feeds
"f-9q5c-metro~losangeles", "f-9q5-metro~losangeles"

## operators with more than 1 feed:
["o-u0j2-gruppotorinesetrasporti", "o-9qbb-marintransit", "o-dr4-dartfirststate", "o-u0j-gttservizioextraurbano", "o-dr4-septa", "o-dr5-nj~transit", "o-dr5r-nyct", "o-c23-soundtransit", "o-u0j82-gttservizituristici", "o-drk-cttransit~hartford", "o-u0p-trentinotrasportieserciziospa", "o-9q5-metro~losangeles"]

## urls used by more than 1 feed:
{
  "http://www.cttransit.com/uploads_GTFS/googleha_transit.zip" : 2,
  "http://dartfirststate.com/information/routes/gtfs_data/dartfirststate_de_us.zip" : 2,
  "http://www.marintransit.org/data/google_transit.zip" : 2,
  "http://www.portauthority.org/GeneralTransitFeed/general_transit_Bing.zip" : 2
}

**Comment by stevevance** [comment]
Delete the following:
- f-9qbb-wwwmarintransitorg: Was never imported, has no associated changesets. 
- f-dr4-dartfirststatecom: Was never fetched, nor imported.

**Comment by drewda** [comment]
@stevevance great, thanks for reviewing!

Re the first 4 feeds you mention, can you use changesets to delete them?

Re the Italy feed that you're trying to access at https://transit.land/dispatcher/feeds/f-u0j-gruppotorinesetrasporti~gttservizioextraurbano~gttservizit I see in the browser console that that's getting a `404 not found error` from the Datastore API. (We'll make this more clear in the Dispatcher https://github.com/transitland/dispatcher/issues/110 )

@irees can you read through Steven's notes in the "Look into" and "operators with more than 1 feed" sections? Let us know which Steven can delete himself using changesets and which you'll need to do on the console.

**Comment by irees** [comment]
Delete via changeset:
f-9qbb-wwwmarintransitorg
f-dr4-dartfirststatecom
f-dppn-wwwportauthorityorg
f-drk-wwwcttransitcom
f-9q5c-metro~losangeles (see #144)

Italian feeds:
It looks like the two Italian feeds have already been deleted -- they're in the OldFeeds table. Deleted by https://transit.land/dispatcher/changesets/2369

CT:
Delete f-drk-wwwcttransitcom
The rest are OK, but these could use better onestop_id's: f-drk-wwwcttransitcom, f-drkh-wwwcttransitcom, f-dr79-wwwcttransitcom

Maybe duplicate:
f-u0pv-ttesercizio and f-u0p-trentinotrasportieserciziospa are OK - leave as is

Rename?:
f-r7h-translinkcomau and f-rhzx-translink already deleted by 
http://transit.land/dispatcher/changesets/2358, http://transit.land/dispatcher/changesets/2394

Operators with more than 1 feed:
-- coming up --

**Comment by stevevance** [comment]
@irees The 5 duplicate feeds have been removed!

**Comment by stevevance** [comment]
How do feeds get renamed?

**Comment by drewda** [comment]
@stevevance do you mean editing the Onestop ID? If so, please list out the current and preferred Onestop IDs. @irees can make this change directly using the app console.

(FYI, in the future, we'll support editing a Onestop ID through a changeset https://github.com/transitland/transitland-datastore/issues/332 )

**Comment by stevevance** [comment]
Existing OnestopID -> proposed new OnestopID:

- f-drkh-wwwcttransitcom -> f-drkh-cttransit~waterbury
- f-dr79-wwwcttransitcom-> f-dr79-cttransit~stamford
- f-drkhr-wwwcttransitcom -> f-drkhr-cttransit~meriden

**Comment by drewda** [comment]
@irees can you edit these feed Onestop IDs on the console?

**Comment by irees** [comment]
```
Feed.find_by_onestop_id!('f-drkh-wwwcttransitcom').update!(onestop_id: 'f-drkh-cttransit~waterbury')
Feed.find_by_onestop_id!('f-dr79-wwwcttransitcom').update!(onestop_id: 'f-dr79-cttransit~stamford')
Feed.find_by_onestop_id!('f-drkhr-wwwcttransitcom').update!(onestop_id: 'f-drkhr-cttransit~meriden')
```

http://transit.land/dispatcher/feeds/f-drkh-cttransit~waterbury
http://transit.land/dispatcher/feeds/f-dr79-cttransit~stamford
http://transit.land/dispatcher/feeds/f-drkhr-cttransit~meriden

**Comment by drewda** [comment]
Thanks, @irees 

Anything else that should happen as part of this ticket, or do you want to close it, @stevevance ?
