### ISSUE TITLE
Manchester Area, UK

### ISSUE THREAD

**Issue by batje** [transitland/transitland#141]
On data.gov.uk I found the GTFS file for the busses & trams in the greater Manchester area, updated monthly. The upload form on transitland says its invalid GTFS. 
Also, not sure if the license is compatible.

https://data.gov.uk/dataset/public-transport-schedules-gtfs/resource/e58f35d3-7404-4d70-b2d3-0eeb3143ccea

**Comment by stevevance** [comment]
This feed duplicates #142
