### ISSUE TITLE
All Public Transport stops in Wales, Scotland & England

### ISSUE THREAD

**Issue by batje** [transitland/transitland#142]
On data.gov.uk all public transport stops in Wales, Scotland & England (so the UK minus Northern Ireland) are published, though there is a disclaimer there are a few hickups with the new system that produces these files. Last fix is from August, so this file is surely maintained:

The upload form says it is invalid:
https://data.gov.uk/dataset/public-transport-schedules-gtfs/resource/e58f35d3-7404-4d70-b2d3-0eeb3143ccea

**Comment by irees** [comment]
Hi @batje 

The url above is an index page, which points to a direct download for the GTFS file 
> http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip

I took a look at the file, and the GTFS data is under the subdirectory `gtdf-out`. You can reference a subdirectory using "#":
> http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip#gtdf-out

I checked and this should work in the Feed Registry. It's a large GTFS feed, so it may stay at "95%" for a few minutes while it's processing.

However, let me leave this issue open for a couple more days while I check how this national integrated feed would interact with some other agencies presently in the registry.

**Comment by stevevance** [comment]
We already have the `http://www.gbrail.info/gtfs.zip` feed with Onestop ID `f-gc-arrivatrainswales~c2c~chilternrailways~crosscountry~eastcoa` that has dozens of train services in England, Scotland, and Wales. Here's an [example operator](https://transit.land/feed-registry/operators/o-gcm-arrivatrainswales) from that feed. 

Are the feeds the same?

**Comment by irees** [comment]
Hi @batje 

I looked, and there's no conflict with existing data. Please feel welcome to submit through the Feed Registry using this url:

http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip#gtdf-out

**Comment by stevevance** [comment]
This feed has now been imported and will soon be available for turn-by-turn directions in the Mapzen Valhalla API.

**Comment by stevevance** [comment]
The Datastore is having trouble processing this large feed, so I've reopened the issue and applied the big feed label.

**Comment by drewda** [comment]
Has been successfully imported.
