### ISSUE TITLE
Some feeds are failing due to "wheelchair_boarding"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#147]
Two feeds that I noticed are failing because of an exception about `wheelchair_boarding`:

- https://transit.land/dispatcher/feeds/f-9qdc-gis4ufresnogov
- https://transit.land/dispatcher/feeds/f-9qd-yosemite~ca~us

**Comment by drewda** [comment]
@irees please look into this when you next have time.

(likely related to https://github.com/transitland/transitland-datastore/issues/672 )

**Comment by irees** [comment]
I think this might have been a spurious issue. During the last prod deploy, I think a couple of jobs might have run with a mismatched version of the code and database. (I think an import might have been enqueued after I started preparing the merge, but I'm not sure.)

I re-imported the feed just now and it succeeded without errors https://transit.land/dispatcher/feeds/f-9qdc-gis4ufresnogov

**Comment by irees** [comment]
I imported another feed with the wheelchair error and it went fine:
https://transit.land/dispatcher/feeds/f-gc3d-catherinemadigan

I'm going to re-import the rest of the feeds that had this error. If all succeed, I'll close this issue as having been a transient issue during a migration.

**Comment by irees** [comment]
No issues on re-imports. Closing.

**Comment by irees** [comment]
Re-opening the issue because it just occurred again: https://transit.land/dispatcher/feeds/f-u2f-dpp

Must be something weird... looking again.

**Comment by irees** [comment]
Not really sure what caused this, my guess is an error in the deploy process, but couldn't answer definitively. I rebuilt the instances and seems to be working OK now. Closing again.
