### ISSUE TITLE
Delete the second Yosemite operator

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#148]
There are two operators for Yosemite (YARTS) using the same feed.

1. [o-9qd-yosemiteareametroaltransportationsystem](https://transit.land/feed-registry/operators/o-9qd-yosemiteareametroaltransportationsystem)
2. [o-9qd-yosemitearearegionaltransportationsystem](https://transit.land/feed-registry/operators/o-9qd-yosemitearearegionaltransportationsystem)

The first one is misspelled so it should be deleted. They both have turn-by-turn, so I believe I can't simply `destroy` it without checking with you first.

**Comment by irees** [comment]
Hmm. This one is interesting.

Deleting the old operator would result in a few (8) stops that aren't served by an operator. However, this might be OK and we can come back and decide to remove these stops as well or not. None of these 8 stops are in the most recent feed version, so we might be able to remove them.

```
["s-9qeqcnnpq3-rushcreek", "s-9qdc7hbd1v-fresnostate", "s-9qdumku65h-bestwesternplusyosemitegatewayinn", "s-9qdvjtud11-tenayalodge", "s-9qdvt1mgv2-bigtreeslodge", "s-9qdyxp2xk1-themajesticyosemitehotel", "s-9qdk66nqfn-mstreetpg~e", "s-9qdyxp88kf-themajesticyosemitehotel"]
```

I checked and Operator `before_destroy_making_history` does remove the `OperatorServingStop` and `OperatorServingRoute` records, so we won't have to remove those manually.

So, I think we can delete the old operator `o-9qd-yosemiteareametroaltransportationsystem` and then I'll come and check everything again on the console.

**Comment by stevevance** [comment]
`o-9qd-yosemiteareametroaltransportationsystem` was deleted successfully.
