### ISSUE TITLE
"licenseAttributionText" doesn't appear in Dispatcher

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#149]
If "licenseAttributionText" has a value, it's not showing in the Dispatcher. 

[This Irish feed](https://transit.land/dispatcher/feeds/f-gc3-burkesbus) has the value "Contains Irish Public Sector Data licensed under a Creative Commons Attribution 4.0 International (CC BY 4.0) licence." but it's not showing in the Dispatcher. It does appear in the [Feed Registry](https://transit.land/feed-registry/operators/o-gc3-burkesbus).

**Comment by drewda** [comment]
@stevevance thanks for noticing. This now works at https://transit.land/dispatcher/feeds/f-gc3-burkesbus
