### ISSUE TITLE
Destroy an Italian feed so I can replace it

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#151]
Is the process for destroying existing operators and feeds straightforward now? 

In the past I've double checked it with @irees because there was a condition where certain records of the database wouldn't be deleted. 

Operator: [o-u0j-atap](https://transit.land/feed-registry/operators/o-u0j-atap)
Its feed: f-u0j-atap

I have a new multi-operator feed that will replace this operator and feed.

**Comment by stevevance** [comment]
If it's not been imported, and it's just a feed, I can destroy it myself. 

If it's an operator, Ian has to delete it because of a bug. 

Until those are resolved, I must run by them to Ian.

**Comment by irees** [comment]
@stevevance I will manually remove this feed, operator, and all other associated entities.

**Comment by stevevance** [comment]
@irees Did you remove it? I can't remember if we talked about this on Slack or not.

**Comment by irees** [comment]
Still some issues with bulk deleting things, the order is very important.

```
feed_onestop_id = 'f-u0j-atap'
f = Feed.find_by_onestop_id!(feed_onestop_id)

c = Changeset.create!(payload: {changes: changes})
['RouteStopPattern', 'Route', 'Stop', 'Operator'].each do |entity_type|
  changes = EntityImportedFromFeed.where(feed: f, entity_type: entity_type).select { |eiff| eiff.entity.imported_from_feeds.count == 1}.map { |eiff| {:action => :destroy, eiff.entity_type.camelize(:lower) => {onestopId: eiff.entity.onestop_id }} }
  if entity_type == 'RouteStopPattern'
    changes.each { |change| change["routeStopPattern"][:geometry] = {}; change["routeStopPattern"][:stopPattern] = [] }
  end
  c.change_payloads.create!(payload: {changes: changes}).payload_validation_errors
end
c.change_payloads.create!(payload: {changes: [{action: "destroy", feed: {onestopId: f.onestop_id}}]})
```

Anyway, deleted in:
https://transit.land/dispatcher/changesets/2675
https://transit.land/dispatcher/changesets/2676
