### ISSUE TITLE
Feed "o-dnr-gotriangleexpress" won't be destroyed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#159]
See [changeset 2737](https://transit.land/dispatcher/changesets/2737). This is a duplicate operator that needs go be deleted.

**Comment by drewda** [comment]
Related: https://github.com/transitland/transitland/issues/50

**Comment by drewda** [comment]
I'm deleting changeset 2737, since it's no longer needed.

For posterity's sake, it was:

```json
{
    "changes": [
        {
            "action": "destroy",
            "operator": {
                "onestopId": "o-dnr-gotriangleexpress"
            }
        }
    ]
}
```
