### ISSUE TITLE
Feed Registry can't download this rural Indiana feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#160]
[ZIP file](http://demopro.nationalrtap.org/admin/GTFSzipFiles/3629/google_transit.zip)

"THERE WAS A PROBLEM DOWNLOADING OR PROCESSING FROM THIS URL."

**Comment by stevevance** [comment]
This GTFS is using non-alphanumeric attribute names.

**Comment by irees** [comment]
Issue in the gtfs wrapper. A column name contains non-alphanumeric characters.

```
NameError: `@' is not allowed as an instance variable name
from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gtfs-dab8bdecccc4/lib/gtfs/model.rb:19:in `instance_variable_set'
```

**Comment by stevevance** [comment]
We haven't discussed this recently. Is there any change?

**Comment by stevevance** [comment]
Still a problem.
