### ISSUE TITLE
Panevezys, Lithuania, feed cannot be downloaded

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#162]
http://www.stops.lt/panevezys/panevezys/gtfs.zip

The Feed Registry reports, "THERE WAS A PROBLEM DOWNLOADING OR PROCESSING FROM THIS URL."

**Comment by irees** [comment]
A geometry or relation issue. Looking into it.

**Comment by irees** [comment]
The underlying issue was resolved and this can now be added to the Feed Registry.

**Comment by irees** [comment]
Hi @stevevance Can you add this feed to the registry & close the issue?

**Comment by stevevance** [comment]
Imported. 
https://transit.land/feed-registry/operators/o-u9cm-panevėžioautobusųparkas
