### ISSUE TITLE
Feed for Lewiston "f-c2hzc-lewistontransitsystem" won't fetch

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#163]
The feed for Lewiston/Ride the Valley hasn't been fetched in the Dispatcher in a reasonable amount of time. 

https://transit.land/dispatcher/feeds/f-c2hzc-lewistontransitsystem

**Comment by irees** [comment]
http://ridethevalley.org/lewistontransitsystem.zip returns `406 - Not Acceptable`

**Comment by stevevance** [comment]
Can't download programmatically.

**Comment by stevevance** [comment]
This is now imported.
