### ISSUE TITLE
Athens, Greece, feed has a ZIP file that appears to be corrupt

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#164]
The Feed Registry won't accept this feed. 

Feed URL: http://geodata.gov.gr/dataset/244cfb87-21a0-4f9f-90af-25e9a232af41/resource/d94179a0-a2bd-432f-8c5e-e05eae2886cf/download/googletransit.zip via http://geodata.gov.gr/dataset/oasa

The feed unzips properly. The `shapes.txt` file is empty.

**Comment by irees** [comment]
https://transit.land/dispatcher/feeds/f-swb-%CE%9F%CF%81%CE%B3%CE%B1%CE%BD%CE%B9%CF%83%CE%BC%CF%8C%CF%82%CE%91%CF%83%CF%84%CE%B9%CE%BA%CF%8E%CE%BD%CE%A3%CF%85%CE%B3%CE%BA%CE%BF%CE%B9%CE%BD%CF%89%CE%BD%CE%B9%CF%8E%CE%BD%CE%9F%CE%91%CE%A3%CE%91~%CE%91thensurbantransportorga

**Comment by stevevance** [comment]
What was the problem @irees?
