### ISSUE TITLE
Romania feed needs to use a subdirectory, but it's not working

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#165]
ZIP file of a GitHub repo. This feed is a Ruby script that converts the schedules from XML to GTFS. 

https://github.com/vasile/data.gov.ro-gtfs-exporter/archive/master.zip#gtfs-out

Why doesn't the hashtag find the subdirectory?

**Comment by irees** [comment]
https://github.com/vasile/data.gov.ro-gtfs-exporter/archive/master.zip#data.gov.ro-gtfs-exporter-master/gtfs-out

**Comment by stevevance** [comment]
So, for ZIP files of GitHub repositories, the repository name is part of the subdirectory name.
