### ISSUE TITLE
Feed Registry won't accept feed for Brest, France

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#166]
Feed: https://applications002.brest-metropole.fr/VIPDU72/GPB/Lot_BrestMetropole_Bibus.zip
Error: THIS FILE DOES NOT APPEAR TO BE A VALID GTFS FEED.

**Comment by irees** [comment]
GTFS::InvalidSourceException: Too many redirects
from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gtfs-dab8bdecccc4/lib/gtfs/url_source.rb:18:in `rescue in load_archive'

**Comment by stevevance** [comment]
@irees Aside from hosting it ourselves, is there a way around this? 
How many redirects is too many?

**Comment by irees** [comment]
The web server has some magic configured; it allows my browser to download the file but fails otherwise.

**Comment by irees** [comment]
I tested it locally and the feed is valid; the redirects are the problem. I'll see why it didn't give a more informative error message.

**Comment by stevevance** [comment]
The outreach opportunity is to inform the agency that their server configuration doesn't allow programmatic downloads, which prevents Transitland from importing this feed.

**Comment by stevevance** [comment]
This feed still has a problem, but only the producer/host can resolve it.
