### ISSUE TITLE
Gwinnett County Transit, Georgia, feed "f-dnh0-gwinnettcountytransit" is outdated

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#170]
The Dispatcher is throwing an exception `GTFS::InvalidSourceException` when fetching [this feed](https://transit.land/dispatcher/feeds/f-dnh0-gwinnettcountytransit). 

The feed is hosted by the [Atlanta Regional Commission](http://www.atlantaregional.com/transportation/transit/existing-regional-transit-system) and has a calendar from 2014. The ARC webpage says that all GTFS files are current as of December 2013. 

This is the only [contact information](http://www.atlantaregional.com/contact-us) I could find.

**Comment by irees** [comment]
please update to:
http://documents.atlantaregional.com/transitdata/gtfs_GCT.zip#GCT_GTFS

**Comment by stevevance** [comment]
Feed URL updated.
