### ISSUE TITLE
An operator in Netherlands "f-u-nl" feed has an erroneous stop location

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#171]
The operator [Aachener Verkehrsverbund (AVV)](https://transit.land/feed-registry/operators/o-u-dkb) has a stop location in the Atlantic Ocean, near Null Island. 
<img width="408" alt="screenshot 2016-10-28 11 59 08" src="https://cloud.githubusercontent.com/assets/1330459/19814908/f0abf664-9d05-11e6-91ba-87981d2158b6.png">

**Comment by stevevance** [comment]
@doublestranded said:
i'm seeing quite a few null island stops in that feed
25 to be exact

example: 
`stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,stop_timezone,wheelchair_boarding,platform_code,zone_id`
`619974,,"Geilenkirchen, Martin-Heyden-StraÃŸe",0.003755,-15.901231,0,stoparea:161230,,,,` 

all 25 of them have lat/lon: `0.003755,-15.901231`

**Comment by batje** [comment]
I looked at the sourcefile, not in depth. 

The source: http://data.ndovloket.nl/avv/ 
The documentation about the source: https://ndovloket.nl/pdf/Beschreibung_Austauschformat_DINO_V1.6_12.01.2010.pdf 

In the zipfile in the /avv/ folder, I opened the file rec_stop.din. I found the busstop at the Martin-Heyden Strasse. I took the X value of the busstop, 2508720, then looked for that value in the file. There is only 1 instance. Which is odd, if you found there are multiple busstops at the same location *after* the transformation to GFRS.

The line:
`7;3210;3210;1;Martin-Heyden-Straße;Martin-Heyden-Straße;;2508720;5647947;Geilenkirchen;5370012;;;`

**Comment by skinkie** [comment]
Is GFRS a typo?

What about the stopping_point table?

**Comment by batje** [comment]
Let me look that up for you.

Ah, it is the same value, and it is also unique in the whole file: 2508720

Could you explain a bit about how that raw data is transformed into GTFS, especially the reprojection into lat/lon?

**Comment by skinkie** [comment]
The one in the NL feed is done from DINO to Bliksem Integration. The alternative one going in to Google is done by KV4J. For AVV the projection used is EPSG:31466.

**Comment by batje** [comment]
ok, so Steve is pulling from http://gtfs.ovapi.nl/ If I understand correctly DINO & Bliksem do that transformation. Is their code opensource? If so, do you know where it is hosted?

**Comment by skinkie** [comment]
Yes, it is open source. But the code isn't the problem here.

**Comment by batje** [comment]
Got it. The projection was really helpful. There are 4 stops with coordinates 0,0. Reprojecting them does not give them lat=0 & lon=0 so that is consistent.
The Martin-Heyden Strasse is not one of them.
# 4350 Spekholzerheide Bf (ZLSM)
# 2340 Arena Kreis D�ren
# 5452 Sekundarschule
# 2650 Bauxhof

The first one I know where it is :-) @skinkie Do you know who operates the other 3 and can fix their sourcefile? Even if we have to provide them with the coordinates?

**Comment by skinkie** [comment]
I know who makes the DINO file, and happy to provide him the the suggestions. And in the mean time keep a list of forked locations. As an example:

```java
  stringStopMap.get("3186").setManualLatLon(50.97069,6.10510, new GTFSUrl("http://openov.de/stop/3186/qa"));
        stringStopMap.get("3210").setManualLatLon(50.96482,6.11958, new GTFSUrl("http://openov.de/stop/3210/qa"));
        stringStopMap.get("3914").setManualLatLon(51.03954,6.21943, new GTFSUrl("http://openov.de/stop/3914/qa"));
        stringStopMap.get("5434").setManualLatLon(50.56880,6.37399, new GTFSUrl("http://openov.de/stop/5434/qa"));
        stringStopMap.get("5452").setManualLatLon(50.60020,6.28795, new GTFSUrl("http://openov.de/stop/5452/qa"));
        stringStopMap.get("2638").setManualLatLon(51.07516,6.30510, new GTFSUrl("http://openov.de/stop/2638/qa"));
        stringStopMap.get("2640").setManualLatLon(51.08024,6.29224, new GTFSUrl("http://openov.de/stop/2640/qa"));
        stringStopMap.get("2358").setManualLatLon(50.79574,6.48493, new GTFSUrl("http://openov.de/stop/2358/qa"));
        stringStopMap.get("6146").setManualLatLon(51.11542,6.15982, new GTFSUrl("http://openov.de/stop/6146/qa"));
        stringStopMap.get("6356").setManualLatLon(51.13868,6.28092, new GTFSUrl("http://openov.de/stop/6356/qa"));
        stringStopMap.get("2102").setManualLatLon(50.90730,6.18165, new GTFSUrl("http://openov.de/stop/2102/qa"));
        stringStopMap.get("4186").setManualLatLon(50.90360,6.37496, new GTFSUrl("http://openov.de/stop/4186/qa"));
```

**Comment by batje** [comment]
I didnt do the final fomatting, but left links into OSM which is easier for debugging now.


4350 Spekholzerheide Hbf 
http://www.openstreetmap.org/#map=17/50.85298/6.02768

Arena Kreis Düren
North side of the street:
http://www.openstreetmap.org/#map=19/50.79267/6.48902
South side
http://www.openstreetmap.org/node/494789500#map=19/50.79257/6.48899
I dont know if GTFS makes a distinction between the 2 sides of the road.

There does not seem to be a bus stop at the Bauxhof in Erkelenz. I looked in different spots, but there only is reference to Gymnasium to the south-east and Hoogerhof to the sout-west
http://www.openstreetmap.org/?mlat=51.08416&mlon=6.30493#map=17/51.08416/6.30493
It would be helpful to know which bussstops come before & affter Bauxhof on which line. At least that would allow for a smarter guess than west of sierra leone.


Sekundarschule, simmerath
https://www.openstreetmap.org/#map=18/50.59988/6.28900

**Comment by batje** [comment]
Ok, now i want this to work so i can tell where to take the bus more accurately than this https://mapzen.com/mobility/explorer/#/isochrones?bbox=5.6174468994140625%2C50.78748927587553%2C6.025657653808594%2C50.91255835156951&isochrone_mode=multimodal&pin=50.8473561840919%2C5.717588430270553 

So @skinkie I hope this is what you were asking for. Can you let us know when this code was applied & run, so @stevevance can retry?
@stevevance Did I miss other busstops?

```
stringStopMap.get("4350").setManualLatLon(50.85298,6.02768, new GTFSUrl("http://openov.de/stop/4350/qa"));
stringStopMap.get("2340").setManualLatLon(50.79267,6.48902, new GTFSUrl("http://openov.de/stop/2340/qa"));
stringStopMap.get("2650").setManualLatLon(51.08416,6.30493, new GTFSUrl("http://openov.de/stop/2650/qa"));
stringStopMap.get("2452").setManualLatLon(50.59988,6.28900, new GTFSUrl("http://openov.de/stop/2452/qa"));

```

**Comment by skinkie** [comment]
@batje not forgotten about this ticket. But making some significant improvements in the _understanding_ how DINO is used in the field, opposed to how it is _documented_. I'll export a dedicated AVV feed shortly so you can see the improvements.

**Comment by stevevance** [comment]
@batje When I created this problem one of our staff found that 25 stops had the `0.003755,-15.901231` coordinates, not `0,0`. 

Thanks for not forgetting about it, @skinkie. I will run the process again when the GTFS feed is updated.

**Comment by skinkie** [comment]
There are currently 6 ambigious trips in the feed remaining. Of which one 
is a validated duplicate. So that did already significantly improve. I am 
a bit hesistant to publish this revamp because it still doesn't do one 
thing that remains to be important for GTFS: merge stops which are at the 
same physical location between versions (DINO exports the entire network 
for each version in a schedule) opposed to versioning for stops which did 
move over time and parent grouping (which is more easy) thereof.

**Comment by batje** [comment]
@stevevance I downloaded the source from before it has been turned in to GTFS from here http://data.ndovloket.nl/avv/ (the zipfile). In that file, there is a rec_stopping_points.din and a rec_stop.din file. Both of those have an X & Y column. There are 4 stops with a unique id that have a 0,0 X&Y in those .din files (in the rec_stopping_points there is 1 double ID so there are 5 rows with 0,0) . If you reproject 0,0 using EPSG:31466 to WGS84 you get 0.003755,-15.901231.

So that is 1 misunderstanding.

I am not sure how the extrapolation to 25 stops work. perhaps 5x5 somewhere? But I guess @skinkie is working on that.

**Comment by skinkie** [comment]
As you might have seen as well; the feed expires soon. So also working on 
getting the new data (in time).

**Comment by batje** [comment]
11 december is a big day in Dutch public transport. A lot of new providers will replace existing ones and the national train timetable will change as well. @stevevance

**Comment by skinkie** [comment]
This is actually the same for a lot of countries; found it for Luxembourg, 
Germany and Belgium.

**Comment by batje** [comment]
Thanks for all the hard work. Seriously cool to be able to use your tools in NL now, too.
