### ISSUE TITLE
Romania feed won't fetch ("f-u8-romania~interregionalcalatori~regiotrans~cfrcălători~softrans~trans")

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#172]
A feed in Romania has a fetch exception. The feed is [f-u8-romania~interregionalcalatori~regiotrans~cfrcălători~softrans~trans](https://transit.land/dispatcher/feeds/f-u8-romania~interregionalcalatori~regiotrans~cfrcălători~softrans~trans)

It has a `Validation error`

Does this have anything to do with #165?

**Comment by irees** [comment]
The feed doesn't have all the required values in `stop_times.txt`; it's invalid. It's missing `arrival_time` or `departure_time` on half the rows.

**Comment by stevevance** [comment]
Is it a frequency-based feed?

**Comment by irees** [comment]
No, it's just an invalid feed. It can't be imported until they fix it.

**Comment by stevevance** [comment]
I enqueued it for import, to see if it's been fixed.
