### ISSUE TITLE
Replace Rome feed by destroying and adding a new feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#174]
The Rome, Italy, feed had an [import problem](https://transit.land/dispatcher/feeds/f-sr2-datimuoviromait). It turns out the ZIP file had been updated to include only a single `readme.txt` file which says the feed URL moved. This coincided with a contributor submitting the new URL to the feed registry. This is great and all, but there's a catch.

The feed at the new URL is very different than the original feed we have. [The original feed has 1 operator](https://transit.land/feed-registry/operators/o-sr2-romaserviziperlamobilitsrl), and the [new feed](https://transit.land/dispatcher/changesets/3057) has 3 operators, excluding the 1 operator in the original feed.

I want the original feed (which has already been imported at L4) to be completely removed so that I can add the new feed and be sure that there's no conflict between objects created by the original feed and objects that will be created by the new feed.

- [ ] Destroy feed "f-sr2-datimuoviromait"
- [ ] Destroy operator "o-sr2-romaserviziperlamobilitsrl"
- [ ] Apply [changeset 3057](https://transit.land/dispatcher/changesets/3057) with the 3 new Rome operators

Payload in [changeset 3084](https://transit.land/dispatcher/changesets/3084) to destroy:
````
{
    "changes": [
        {
            "action": "destroy",
            "feed": {
                "onestopId": "f-sr2-datimuoviromait",
                "url": "http://dati.muovi.roma.it/gtfs/google_transit.zip"
            }
        },
        {
            "action": "destroy",
            "operator": {
                "onestopId": "o-sr2-romaserviziperlamobilitsrl"
            }
        }
    ]
}
````

**Comment by irees** [comment]
- [ ] Compare with archived gtfs
- [ ] Decide if old operator maps to new operator; if so, carry over; if not, delete

**Comment by stevevance** [comment]
I compared the new feed with the archived GTFS. 

The archived (original) feed has a lot of the same routes as the new feed, but ascribes all of them to 1 operator called MOBILITA. 

The new feed, on the other hand, ascribes them to one of 3 operators, with more specific names like ATAC (the subway and main bus company), TPL (another bus company), and Trenitalia (for the commuter rail).

The new feed also has 7 additional routes.

We are going to destroy the old operator, the old feed, and import the new feed. We will not remove any existing routes, stops, or route-stop pairs. The stops/routes that match up will match up during import. We can clear out any that didn't match up from the old feed later.

**Comment by stevevance** [comment]
There was a problem applying this changeset. After clicking the "apply changeset" button, it times out and shows a 504 error.

**Comment by stevevance** [comment]
This was taking a while, so @irees pushed it through via the console.

**Comment by irees** [comment]
Rome feed is now updated.
