### ISSUE TITLE
Outreach opportunities

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#175]
There are 2 outreach opportunities listed here. 

**1. Akron, OH**
Their website advertises that you can use Google Maps to plan a transit trip in the town. There's an email address on this page. 

<a href="http://www.akronmetro.org/metro-trip-planner.aspx"><img width="699" alt="screenshot 2016-11-04 16 22 50" src="https://cloud.githubusercontent.com/assets/1330459/20022947/f0c1fe82-a2aa-11e6-9cfb-c9b317699ef9.png"></a>

**2. St. Louis, MO**
[Metro St. Louis](http://www.metrostlouis.org/About/DeveloperResource.aspx) hosts their GTFS feed on FTP (see #34), but Transitland currently handles only HTTP. They are already hosting their real-time protocol buffers on HTTP. There's an email address on this page to contact someone.

**Comment by drewda** [comment]
We've already got our hands full with feeds that are accessible. Closing this for now, although we can always revisit if there's an occasion to have a conversation with either agency or locals with a need for that data.
