### ISSUE TITLE
Trenitalia operator "o-s-trenitalia" has no operator service area

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#176]
The [Trenitalia operator](https://transit.land/feed-registry/operators/o-s-trenitalia) (which is a national brand for intercity and suburban rail service in Italy) is served by 7 feeds. 

The operator service area's [GeoJSON file](https://transit.land/api/v1/operators/o-s-trenitalia.geojson) is empty (well, it says "null").

**Comment by drewda** [comment]
Let's handle this as part of https://github.com/transitland/transitland/issues/122, starting by putting in a temporary geography for the operator (through a manual changeset).

**Comment by stevevance** [comment]
This is related to #122 - the changeset included a manually-created operator with no operator service area. And there are problems importing the 7 contributing feeds, so that means they wouldn't be expanding the operator service area bounding box.
