### ISSUE TITLE
HART missing routes, stops, schedules

### ISSUE THREAD

**Issue by nselikoff** [transitland/transitland#178]
The HART (Tampa, Florida, USA) feed is in the registry, but doesn't show routes, stops or schedules: https://transit.land/feed-registry/operators/o-dhv-hillsborougharearegionaltransit

Here's the feed on transitfeeds.com, showing that the data is there and valid: http://transitfeeds.com/p/hillsborough-area-regional-transit/228

**Comment by stevevance** [comment]
Hi @nselikoff, thanks for telling me about this. HART had never been imported. I've set it to be imported the next time our system imports feeds. After that import happens the routes, stops, and schedules will appear.

**Comment by nselikoff** [comment]
Thanks @stevevance 👍

**Comment by stevevance** [comment]
@nselikoff They're there now.
