### ISSUE TITLE
Finnish feed "f-u6x-turunlinja~autoilijainosakeyhtiö~savonlinjaoy~sl~autolinja" won't import

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#180]
This Finnish feed `f-u6x-turunlinja~autoilijainosakeyhtiö~savonlinjaoy~sl~autolinja` [dispatcher](https://transit.land/dispatcher/feeds/f-u6x-turunlinja~autoilijainosakeyhtiö~savonlinjaoy~sl~autolinja) won't import. 

The specific exception is `undefined method 'tproj' for nil:NilClass`

**Comment by doublestranded** [comment]
see #881

**Comment by stevevance** [comment]
The 881 issue didn't automatically link for me. What's that issue about?

**Comment by doublestranded** [comment]
Sorry about that! I added the proper link.
