### ISSUE TITLE
GTFS Agency ID for London, Ontario, feed "f-dpwh-londontransit"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#182]
The feed `f-dpwh-londontransit` [dispatcher](https://transit.land/dispatcher/feeds/f-dpwh-londontransit) is set to look for an operator in the feed with the `gtfsAgencyId` named `LTC - September 2016 Schedules`. 

The current feed that I [downloaded](http://www.ltconline.ca/gtfsfeed/google_transit.zip) has two different agency IDs:
- LTC -November 2016 Schedules
- LTC -september  2016 Schedules rev 3.0

They are the same operator. 

If the agency ID in the Feed Registry was set to `null`, would datastore find both of the operators?

**Comment by irees** [comment]
No, there has to be an explicit link between each GTFS `agency_id` and TL Operators.

**Comment by stevevance** [comment]
This was fixed in our conversation the other day. When I wrote this issue I didn't know about `doesNotIncludeOperators` and I didn't see that one of the Agency IDs had a double space in it.
