### ISSUE TITLE
Two Colombian feeds have missing data

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#185]
These two feeds from Colombia have fetch errors. 

1. https://transit.land/dispatcher/feeds/f-66jh-vinabussa~trolebuseschilesa~busesdelgranvalparaisosa~topt - resulting in [this issue](https://transit.land/dispatcher/issues/feed-fetch/169444)
2. https://transit.land/dispatcher/feeds/f-67vc-transantofagasta - resulting in [this issue](https://transit.land/dispatcher/issues/feed-fetch/169452)

They have identical problems:

> **feed_fetch_invalid_source**
GTFS feed does not contain the required files, or there was an unknown problem with fetching.

What is the missing information?

I double checked; these are the current URLs, which come from [this data portal](http://datos.gob.cl/dataset?q=gtfs).

**Comment by irees** [comment]
The server seems flaky -- sometimes it succeeds with a valid zip file, sometimes it returns an error. Tried several times locally. I also manually refetched in Dispatcher, and after a few attempts both had a successful fetch and the issue went away. But if the server is weird, it may re-appear.
