### ISSUE TITLE
Multiple operators in London, Ontario, changeset was misapplied

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#191]
I applied [this changeset](https://transit.land/dispatcher/changesets/3606), and it was accepted, but it didn't work as I expected.

````
{
    "changes": [
        {
            "action": "createUpdate",
            "feed": {
                "onestopId": "f-dpwh-londontransit",
                "url": "http://www.ltconline.ca/gtfsfeed/google_transit.zip",
                "includesOperators": [
                    {
                        "gtfsAgencyId": "LTC -November 2016 Schedules",
                        "operatorOnestopId": "o-dpwh-londontransit"
                    },
                    {
                        "gtfsAgencyId": "LTC -september  2016 Schedules rev 3.0",
                        "operatorOnestopId": "o-dpwh-londontransit"
                    }
                ],
                "doesNotIncludeOperators": [
                    {
                        "gtfsAgencyId": "LTC - September 2016 Schedules",
                        "operatorOnestopId": "o-dpwh-londontransit"
                    }
                ]
            }
        }
    ]
}
````

I removed one of the operators but it's still showing in [the Dispatcher](https://transit.land/dispatcher/feeds/f-dpwh-londontransit). 

<img width="831" alt="pasted_image_12_11_16__19_30" src="https://cloud.githubusercontent.com/assets/1330459/21085489/5f59b188-bfd8-11e6-9cf2-166e778bd44d.png">

**Comment by irees** [comment]
hi @stevevance 

Looks like it has two spaces - argh. When it's rendered in dispatcher as html, all whitespace is collapsed to a single space. I'll make a note to render it as whitespace preserving code, not text.

See:
http://transit.land/api/v1/feeds/f-dpwh-londontransit

```
"gtfs_agency_id": "LTC - September  2016 Schedules",
"operator_onestop_id": "o-dpwh-londontransit",
```

So the `doesNotIncludeOperators` should work if you redo it with the extra space.

**Comment by stevevance** [comment]
worked.
