### ISSUE TITLE
Emory University feed "f-dnh01-cliffshuttles~emoryuniversity" fails to import because of validation issue

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#192]
The Emory University shuttle bus feed [dispatcher](https://transit.land/dispatcher/feeds/f-dnh01-cliffshuttles~emoryuniversity) failed to import because of a validation error.

**Comment by irees** [comment]
Missing require data in `stop_times.txt`:

```
Invalid Value
Invalid value in field arrival_time
The last stop_time in trip 1136613 is missing times.
```

**Comment by drewda** [comment]
Looks like this import succeeded on Mon Feb 06 2017
