### ISSUE TITLE
Update Maryland feed URLs

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#193]
A lot of Maryland transit feeds have moved to a URL, which are listed on the [MDTrip website](http://www.mdtrip.org/commuter-tools/developer-resources/).

Fixed Allegany and added Charles County VanGO.

**Comment by drewda** [comment]
@stevevance if this is still relevant, can you work through updated the URLs on MDTrip feeds that have changed and add any that aren't already in Transitland?
