### ISSUE TITLE
Manage existing and future Paris, France, feeds

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#197]
An overview of existing imported feeds:
- `f-u09-ratp`, from RATP, which includes Paris Métro, bus, RER A and B, and tram routes 1-3 and 5-8 (T4 is operated by another company), some buses in other cities, some night buses, and the airport VAL shuttles. 
- `f-u0-sncf~tram~train~ter`, from SNCF, which includes 4 tram-train routes (tram service in urban areas that can use mainline tracks), and 4 routes – all in cities outside of Paris

We are going to import 3 feeds:

- [x] `f-u0-sncf~ter` - this import failed on the first time, because ````undefined method `onestop_id' for nil:NilClass````  ([see feed page in Dispatcher](https://transit.land/dispatcher/feeds/f-u0-sncf~ter))
- [x] `f-u0-sncf~transilien~rer` - this is from SNCF and has detailed information on all RER and Transilien routes import everything except Agency ID `DUA850` which is only Paris tram route 4. 
- [x] `f-u09-paris~metro~bus~tram` - this is from STIF, the network coordinator in Paris. We will import everything except Agency IDs `741`, `742`, and `743` (which represent RER, Transilien, and TER routes, because those come with better detail in other feeds we are imported). Also, change the feed's Onestop ID to something more useful like `f-u09-stif`. 

After the 3 feeds are imported we will remove RATP because its information will be superseded by the new imports. 
- [x] `f-u09-ratp` - remove this by hand

Remove because superseded
- [x] `f-u0-sncf~transilien`

We are able to remove 1 feed immediately from the datastore (it has not been imported):
- [x] `f-u-sncf~intercites` because it would overlap `f-u0-sncf~ter` (and TER has more data)

(onestopids updated by ian)

**Comment by doublestranded** [comment]
On January 7, 2017 I extended the services for the 'metro', 'tram', and 'rail' routes of the active `f-u09-ratp` feed version, which had all expired before January 1, 2017. I extended their services to April 4, 2017 - the latest calendar date of the feed. I used this query:

feed = Feed.find_by_onestop_id!(‘feed-onestop-id')
ScheduleStopPair.where(route_id: Route.where_imported_from_feed(feed).where_vehicle_type(['metro','rail','tram']).ids).find_in_batches{|ssp_batch| ScheduleStopPair.where(id: ssp_batch).update_all(service_end_date: '20170404’)}

**Comment by stevevance** [comment]
The new feed `f-u0-sncf~transilien~rer` ([dispatcher](https://transit.land/dispatcher/feeds/f-u0-sncf~transilien~rer)) supersedes `f-u0-sncf~transilien` because it has the selective imports. The new feed has two operators: SNCF for the 5 Transilien (train) routes, and RATP for the 5 RER routes.

**Comment by stevevance** [comment]
When it's easy, change `f-u09-paris~metro~bus~tram` to `f-u09-stif~paris~metro~bus~tram`.

**Comment by irees** [comment]
Final status:

Kept feeds:
- [x] f-u0-sncf~tram~train~ter
- [x] f-u0-sncf~transilien~rer
- [x] f-u09-paris~metro~bus~tram

Removed feeds:
- [x] f-u0-sncf~ter (-> f-u0-sncf~tram~train~ter)
- [x] f-u09-ratp
- [x] f-u-sncf~intercites
