### ISSUE TITLE
Only 1 route in Irish Rail feed <f-gc6-irishrail~irishrail~irishrail~irishrail> was imported

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#206]
There are 23 routes in the GTFS feed for [Irish Rail](https://transit.land/feed-registry/operators/o-gc-irishrail) ([dispatcher](https://transit.land/dispatcher/feeds/f-gc6-irishrail~irishrail~irishrail~irishrail)), but only one of them was imported.

**Comment by drewda** [comment]
@stevevance looks like you'll need to update the operator-in-feed associations on this feed:

![transitland dispatcher 2017-03-06 14-40-07](https://cloud.githubusercontent.com/assets/212369/23633489/ce50164c-027a-11e7-8e55-5470deb4ab38.png)

That will likely bring in all of the routes.

**Comment by stevevance** [comment]
changed the operators' `gtfsAgencyId` in the feed object
