### ISSUE TITLE
review and update feeds managed by MJC

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#209]
Transitland includes some feeds managed by MJC. @stevevance please review their list (http://mjcaction.com/clients_gtfs.html) and add any that are missing to the Feed Registry.

**Comment by stevevance** [comment]
These are still in progress and you can find them by searching for feeds with the tag `managed_by=mjc`.

**Comment by drewda** [comment]
All added, tagged, and imported: https://transit.land/dispatcher/feeds?tag_key=managed_by&tag_value=mjc
