### ISSUE TITLE
switch operator geography at country and state level to ISO-3166

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#211]
Operator geography at the country and state level is currently set using names provided by Who's on First (WOF).

The WOF administrative hierarchy has more levels, and so trying to capture certain geographies with just country/primary and state/secondary fields has been problematic. For example United Kingdom vs. Whales, as well as the multiple levels of subdivisions that WOF provides for Italy.

Also, to query the API by country or state also currently requires knowing a fully expanded string value. For example: http://transit.land/api/v1/operators?country=United%20States

To simplify operator geographies, let's switch to using [ISO-3166-1 alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) for the country field and [ISO-3166-2 codes](https://en.wikipedia.org/wiki/ISO_3166-2) for the state field. Clients, including Feed Registry, can choose to expand the codes to full names for their own display or search purposes (e.g., `US` to `United States`)

TODO:

1. [x] @drewda: prepare CSV that lists all operators, along with current `country` and `state` values, for editing
2. [x] @stevevance: edit changeset `country` and `state` values for all operators to use ISO-3166 values
3. [x] @drewda: Feed Registry: switch "add a feed" drop-downs to have ISO-3166 values. Potentially using [iso-3166-2 npm package](https://www.npmjs.com/package/iso-3166-2)
4. [x] @drewda: Feed Registry: when displaying country and state values, expand to full name
5. [x] @drewda: Feed Registry: when searching by country or state, expand to full name
6. [x] @drewda: turn CSV into changeset, apply the changeset, and merge in the Feed Registry changes at the same time
7. [ ] @stevevance: do a final check to see that all country/state values have been updated and no new additions have slipped through in the meantime using the old scheme

Side notes:
- Conflating against WOF admin hierarchy is still relevant for other entities, including stops/stations: https://github.com/transitland/transitland-datastore/issues/312)
- For now, we'll still only allow one set of country/state/metro values per operator. For operators that span multiple geographies, we'll continue to reference the headquarters location. In the future, we'll consider supporting multiple geographies per level.

//cc @leofr

**Comment by LeoFR** [comment]
+1 on that!

**Comment by stevevance** [comment]
@drewda When are those completed tasks going to be pushed to production? Is that when I should start using ISO codes?

**Comment by drewda** [comment]
@stevevance here's a CSV that lists out all current operator Onestop IDs, current country value, and current state value:

[operator-country-and-state-values-13feb2017.csv.txt](https://github.com/transitland/transitland/files/772666/operator-country-and-state-values-13feb2017.csv.txt)

Please work through and switch to  [ISO-3166-1 alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) codes for country and [ISO-3166-2 codes](https://en.wikipedia.org/wiki/ISO_3166-2) codes for state.

Should be straightforward to open this in Excel or another piece of spreadsheet software and sort and update multiple values at once.

Once you have a new CSV file, I can help turn it into a changeset that we can apply.

In terms of timing, we can apply the changeset and then deploy the Feed Registry updates to production right after.

**Comment by drewda** [comment]
Note to self, console commands used to generate the CSV:

```ruby
require 'csv'
rows = Operator.pluck(:onestop_id, :country, :state)
csv_str = rows.inject([]) { |csv, row|  csv << CSV.generate_line(row) }.join("")
```

**Comment by stevevance** [comment]
@drewda I'll start working on that this week.

**Comment by drewda** [comment]
A little Ruby script to turn that CSV into a changeset: https://gist.github.com/drewda/c0272a5e5a3f02569ff8604218f8c0b8

**Comment by drewda** [comment]
Here's the changeset that the script produced from the CSV: https://transit.land/dispatcher/changesets/4791

@stevevance have a look and see if this looks good to you.
