### ISSUE TITLE
AWS links broken for active feed versions

### ISSUE THREAD

**Issue by ethanpooley** [transitland/transitland#214]
I don't know how many feeds are affected; I checked Caltrain and BART. The AWS links for previous feed versions (`is_active_feed_version=false`) are working. Apologies if I'm missing something simple. This is my first day working with the API.

Example feed version (Caltrain): https://transit.land/api/v1/feed_versions/17ec08c8bccac0683976a1fc2a286533b0e039b5

That feed's AWS link: https://s3.amazonaws.com/transit.land/datastore-uploads/feed_version/fd0bf2327f8034ceabff6d914220531def1e3903.zip

The AWS response:
```
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>datastore-uploads/feed_version/fd0bf2327f8034ceabff6d914220531def1e3903.zip</Key>
    <RequestId>791370E6EA57FCC6</RequestId>
    <HostId>a5RraMQnQXjw78o7pGwDvYmgxz93v/oquuNWxNDBxJiIeZkmKqUn7N9mXsdMNaDBGGER0MkIKJ4=</HostId>
</Error>
```

**Comment by irees** [comment]
Hi @ethanpooley

We recently renamed the files in our s3 bucket, it looks like a few may have been missed. Looking into it now. Thanks for the heads-up.

**Comment by irees** [comment]
hi @ethanpooley 

The issue should be resolved -- let me know if you find any similar problems. Thanks!

**Comment by drewda** [comment]
Probably an after-effect of https://github.com/transitland/transitland-datastore/issues/895 on a small subset of feeds.

Thanks for reporting the issue, @ethanpooley, and thanks for fixing so quickly, @irees!
