### ISSUE TITLE
review and add missing feeds managed by Trillium

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#215]
Last March we bulk added many feeds managed by Trillium (see https://transit.land/dispatcher/changesets/682 and https://github.com/mapzen/transitland-internal/issues/12). They have since added more feeds.

Here's their current list of publicly available feeds:
https://docs.google.com/spreadsheets/d/1wdnNkPq6Bo6BAz-5kN1nOSJCRR_V9s-HRtQRRBQxrXU/edit#gid=0 I've also added a sheet to that spreadsheet that lists out URLs of Trillium-managed feeds that are already in Transitland. Hopefully that will speed the process of working through the new list, figuring out which feeds aren't already in Transitland, and adding those to the Feed Registry.

**Comment by drewda** [comment]
In the future, we should ease this process by adding functionality to Dispatcher that allows checking a list of feed URLs and seeing which are already present in Transitland.

**Comment by stevevance** [comment]
@drewda Should I add `"managed_by": "Trillium"` as a feed tag?

**Comment by stevevance** [comment]
@drewda Here's the proposed changeset that will add the "managed_by=trillium" tag to the feeds that didn't already have the tags. https://transit.land/dispatcher/changesets/5019

18 new feeds were added.

**Comment by drewda** [comment]
@stevevance 👍

**Comment by drewda** [comment]
I pointed the Trillium crew to https://transit.land/dispatcher/feeds?per_page=%E2%88%9E&tag_key=managed_by&tag_value=trillium in case they want to review.
