### ISSUE TITLE
Operator "Østfold kollektivtrafikk" seems to exist in Feed Registry, but isn't found

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#216]
Steps to replicate:
1. Go to Feed Registry
2. Search for "Østfold kollektivtrafikk" (which is in Norway)
3. FR finds this in the `<select>` menu but has no results. 

[Quick link](https://transit.land/feed-registry/?name=Østfold%20kollektivtrafikk)

This is related to a [submitted feed](https://transit.land/dispatcher/changesets/4868/change-payloads/47476/edit)

**Comment by drewda** [comment]
Appears to be a problem with how we make operator names queries case insensitive. Lowercasing the name column in Postgres is leading to a different value than lowercasing the name string in Ruby:

```ruby
irb(main):005:0> Operator.where(Operator.arel_table[:name].lower.in(['Østfold kollektivtrafikk'.downcase])).count
=> 0
irb(main):006:0> Operator.where(Operator.arel_table[:name].in(['Østfold kollektivtrafikk'.downcase])).count
=> 1
```

Probably simplest to just make operator-look-up-by-name case sensitive: https://github.com/transitland/transitland-datastore/pull/1004

**Comment by drewda** [comment]
Scratch that. Turns out that Postgres is properly doing the lower-casing:

```sql
transitland-4-5-0=> select lower('Østfold kollektivtrafikk');
          lower
--------------------------
 østfold kollektivtrafikk
```

It's actually a problem on the Ruby side.

Better solution coming in a minute on the PR.
