### ISSUE TITLE
remove identifiers

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#217]
Now that `EntityImportedFromFeed` records include GTFS IDs, we have little need for `identifiers`. It's actually simpler to just use tags.

- [x] @stevevance: data: move US NTDs from identifiers to tags on production servers: https://transit.land/dispatcher/changesets/4975
- [x] @drewda: Datastore: remove code and drop identifier columns from database: https://github.com/transitland/transitland-datastore/pull/1011
- [x] @drewda: Feed Registry: remove from operator details page: https://github.com/transitland/feed-registry/pull/386
- [x] @drewda: website: remove from docs: https://github.com/transitland/www-transit-land/commit/79ad6b9da8568e37908a843bbe9925db440e6b6a

**Comment by drewda** [comment]
I've prepped a changeset that moves one US NTD per operator from `identifiers` over to `tags`: https://transit.land/dispatcher/changesets/4975

Here's the code I used to create this changeset:
```ruby
operators_with_us_ntd_ids = Operator.with_identifier_starting_with('usntd')

modified_operators = []

operators_with_us_ntd_ids.each do |o|
  modified_operator = Operator.new(
    onestop_id: o.onestop_id,
    tags: {
      us_ntd_id: o.identifiers.select {|s| s.starts_with?('usntd') }.first.match(/(\d+)/)[0]
    }
  )
  modified_operators << modified_operator
end

changeset = Changeset.create(notes: 'moving US NTD IDs from identifiers to tags')
changeset.create_change_payloads(modified_operators)
changeset.save!
```

**Comment by drewda** [comment]
One downside of tags is that they don't give an easy way to store and search for multiple values for the same key. This makes it hard to store two US NTD IDs for New York City MTA: https://transit.land/feed-registry/operators/o-dr5r-nyct

Since this is the only example I've found of an operator that has more than one US NTD ID, we'll just store the two values in tags as `us_ntd_id` and `us_ntd_id2` for the time being.

**Comment by drewda** [comment]
@stevevance please review and edit the changeset that moves over US NTD IDs: https://transit.land/dispatcher/changesets/4975

(Note that there seems to be some typos in the current US NTD IDs in the `identifiers`--a few operators have more than one US NTD ID, with the difference just being an extra zero--so it's worth a quick check through all of these values that are being moved over to tags to make sure we're saving the right ID.)

**Comment by stevevance** [comment]
Ones to double check:
- o-9q8y-sfmta: 9015 (4 digits instead of the typical 5)
- o-9q9-vta: 9013
- o-9q8-samtrans: 9009
- o-drmg-marthasvineyardtransitauthority, o-drs-franklinregionaltransitauthority, o-drq4-thewave~nantucketregionaltransitauthority, o-dr-peterpanbuslines: 1 (1 digit)
- o-dqch-prtc: 30070 (proper trailing zero?)
- o-9q9-bart: 9003
- o-dr5r7-nycdot: 2082

**Comment by stevevance** [comment]
@drewda The changeset is applied.

**Comment by drewda** [comment]
@stevevance 👍  thanks for correcting!

**Comment by drewda** [comment]
Closing because all the active work is done here.

The code and database changes will go out with the next Datastore production release: https://github.com/transitland/transitland-datastore/pull/1013
