### ISSUE TITLE
Replace a Torino, Italy, feed with a new one

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#219]
I need to delete 4 operators and 1 feed, and replace it with a feed that has the same 4 operators and what appears to be more information. The replacement feed is also hosted on the operator's own website, whereas the existing feed is hosted on the city's data portal. 

`f-u0j-torino` has the URL `http://opendata.5t.torino.it/gtfs/torino_it.zip`

## Existing feed operators
- o-u0j2-gruppotorinesetrasporti: `GTT`
- o-u0j-gruppotorinesetrasporti: `GTT_F`
- o-u0j-gttservizioextraurbano: `GTT_E`
- o-u0j82-gttservizituristici: `GTT_T`

Changesets to destroy [the operators](https://transit.land/dispatcher/changesets/5023) and [the feed](https://transit.land/dispatcher/changesets/5024).

## Replacement feed
https://transit.land/dispatcher/changesets/5003 (which uses this URL `	http://www.gtt.to.it/open_data/gtt_gtfs.zip`)

Which has these operators:
- GTT Servizio Urbano: `U`
- GTT Servizio Ferroviario: `F`
- GTT Servizio Extraurbano: `E`
- GTT Servizi Turistici: `T`

F, E, and T have obvious matches, but where does `U` come from? Does `U` match the existing `GTT`? They have the same geohashes. 

`T`'s geohash (o-u0j2-gttservizituristici) is quite different from `GTT_T`'s geohash (o-u0j82-gttservizituristici).

**Comment by stevevance** [comment]
@irees Can you check this out and make sure I'm not missing anything?

**Comment by irees** [comment]
in changeset, rename the following onestop IDs:

E
`o-u0j-gttservizioextraurbano -> o-u0j-gttservizioextraurbano`

F
`o-u0j-gttservizioferroviario -> o-u0j-gruppotorinesetrasporti`

T
`o-u0j2-gttservizituristici -> o-u0j82-gttservizituristici`
(stays the same)

U
`o-u0j2-gttserviziourbano -> o-u0j2-gruppotorinesetrasporti`

**Comment by stevevance** [comment]
All updated!
Check the feed for proper import. 
https://transit.land/dispatcher/feeds/f-u0j-torino
