### ISSUE TITLE
There's another source for Switzerland feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#220]
Someone [replied](https://twitter.com/chtrachsel/status/839235366825701384) to the Transitland Twitter account with a link to some another source for a Swiss feed. 

https://opentransportdata.swiss/en/dataset/timetable-2017-gtfs

I don't know if this is different from our current source on http://gtfs.geops.ch/

**Comment by drewda** [comment]
Moving over to https://github.com/transitland/transitland/issues/52#issuecomment-285745865
