### ISSUE TITLE
Several feeds are missing a stop

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#226]
Pace, Chicago: [f-dp3-pace](https://transit.land/dispatcher/feeds/f-dp3-pace)
Champaign, IL: [f-dp1h-champaignurbanamasstransitdistrict](https://transit.land/dispatcher/feeds/f-dp1h-champaignurbanamasstransitdistrict)
Ouibus (France): [f-u0-ouibus](https://transit.land/dispatcher/feeds/f-u0-ouibus)
Czechia: [f-u2f-dpp](https://transit.land/dispatcher/feeds/f-u2f-dpp)
Allentown (LANTA): [f-dr4r-lanta](https://transit.land/dispatcher/feeds/f-dr4r-lanta)
Budapest: [f-u2m-bkk](https://transit.land/dispatcher/feeds/f-u2m-bkk)
St. Louis: [f-9yzg-metrostlouis](https://transit.land/dispatcher/feeds/f-9yzg-metrostlouis)
Transilien: [f-u0-sncf~transilien~rer](https://transit.land/dispatcher/feeds/f-u0-sncf~transilien~rer)
Metrobus (CA): [f-fb6q-metrobus](https://transit.land/dispatcher/feeds/f-fb6q-metrobus)
Manchester: [f-gcw-greater~manchester](https://transit.land/dispatcher/feeds/f-gcw-greater~manchester)
Saskatoon: [f-c9k0-saskatoontransit](https://transit.land/dispatcher/feeds/f-c9k0-saskatoontransit)
Venice, Italy: [f-u20-actvspa](https://transit.land/dispatcher/feeds/f-u20-actvspa)
Vilnius: [f-u99z-sĮsusisiekimopaslaugos](https://transit.land/dispatcher/feeds/f-u99z-sĮsusisiekimopaslaugos)
Hamilton, ON: [f-dpxj-hamiltonstreetrailway](https://transit.land/dispatcher/feeds/f-dpxj-hamiltonstreetrailway)
Utah: [f-9x0-uta](https://transit.land/dispatcher/feeds/f-9x0-uta)
l'Outaouais, QC, CA: [f-f244-sto](https://transit.land/dispatcher/feeds/f-f244-sto)
Paris Métro: [f-u09-paris~metro~bus~tram](https://transit.land/dispatcher/feed-versions/74b2cb33249ce0a5ac3a4ad83e80a5278296f8df)
Switzerland: [f-u0-switzerland](https://transit.land/dispatcher/feed-versions/cc46fbaf29672f805c4388fa44ad74debd80b7e2) - check again
Montgomery, MD: [f-dqc-montgomerycountymdrideon](https://transit.land/dispatcher/feed-versions/2ecd8be61f9138a4a1f0bbf2ffd36c5aa00dffe2)
Rhein-Neckar, Germany: [f-u0y1-rhein~neckar~verkehrgmbhrnv](https://transit.land/dispatcher/feed-versions/f60fa131fb0c6ae3b890580c413f2cffe78e1e13)
Cherriots (Salem, OR): [f-9rb-cherriots](https://transit.land/dispatcher/feed-versions/fc3fa80bb284f73cae1afaabb1bdde1dbdd82d19)
Flixbus (Europe): [f-u-flixbus](https://transit.land/dispatcher/feed-versions/fb70becf6f8ade27a8cbd92d55ee7827c393fbf4)
This Finland feed: [f-udc-lehdonliikenneoy~hämebusoy~pekolanliikenneoy~mikkolanliike](https://transit.land/dispatcher/feed-versions/ad2a223105c8200d7c445de14ce68ddf12278b06)
Duke, NC: [f-dnrug-duke~nc~us](https://transit.land/dispatcher/feed-versions/5072903f0b87228566d4d016af651e8f747a5a96)

Import exception: "Changeset::Error Couldn't find Stop"

**Comment by drewda** [comment]
Should be resolved by https://github.com/transitland/transitland-datastore/pull/1037

**Comment by stevevance** [comment]
@drewda @irees Do you know when the graph refactor will be published?

**Comment by drewda** [comment]
Reopening this issue, so @stevevance has the list of feeds to reimport. That can happen once @irees releases #1037 to production servers.

**Comment by stevevance** [comment]
I have enqueued the following:

Pace, Chicago: [f-dp3-pace](https://transit.land/dispatcher/feeds/f-dp3-pace)
Champaign, IL: [f-dp1h-champaignurbanamasstransitdistrict](https://transit.land/dispatcher/feeds/f-dp1h-champaignurbanamasstransitdistrict)
Ouibus (France): [f-u0-ouibus](https://transit.land/dispatcher/feeds/f-u0-ouibus)
Czechia: [f-u2f-dpp](http://opendata.iprpraha.cz/DPP/JR/jrdata.zip)

**Comment by stevevance** [comment]
@irees Switzerland doesn't seem to want to finish imported: [check this feed version](https://transit.land/dispatcher/feed-versions/93f909ebbc820786fcad36d4939458e3c2df7401).

**Comment by drewda** [comment]
@stevevance can this issue be closed? or are there impacted feeds remaining to reimport? (If it's only the Swiss feed remaining, it's fine to close this issue -- we can track all Swiss-related issues under #52)
