### ISSUE TITLE
Feeds with error "Changeset::Error undefined method `onestop_id' for nil:NilClass"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#228]
- Rhode Island Public Transit Authority "f-drm-rhodeislandpublictransitauthority" - [error](https://transit.land/dispatcher/feed-versions/27b09c6e7624a08c4d38480580db003f2acb95d3)

Resolved/not applicable anymore:
- GO Transit in Toronto: https://transit.land/dispatcher/feeds/f-dpz-gotransit (resolved)
- Barcelona: https://transit.land/dispatcher/feeds/f-sp3e-tmb - now has issue #272

**Comment by irees** [comment]
This may be an issue in quality check, or it could be something elsewhere surfacing in quality check. @doublestranded

**Comment by stevevance** [comment]
@irees Neither of these feeds is working.

**Comment by irees** [comment]
@stevevance looking into it today

**Comment by stevevance** [comment]
The error on the Barcelona (TMB) feed is now "stack level too deep".

**Comment by stevevance** [comment]
Toronto still fails as of June 11, 2017.

**Comment by stevevance** [comment]
I got `undefined method 'id' for nil:NilClass` on a Rhode Island [feed version import failure](https://transit.land/dispatcher/feed-versions/cbe56f9d63ba0c159ea311883aa391ff8e58b333). Is that the same or a different error? @irees

**Comment by stevevance** [comment]
Rhode Island now has a different error, #276
