### ISSUE TITLE
Some feeds have this problem: "no implicit conversion from nil to integer"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#229]
https://transit.land/dispatcher/feeds/f-u-nl
https://transit.land/dispatcher/feeds/f-u0j-piemonte~autobus

`{:exception_log=>"\nno implicit conversion from nil to integer\n...`

**Comment by irees** [comment]
Looks like an issue in `closest_point_on_segment` / `gtfs_shape_dist_traveled` @doublestranded

**Comment by doublestranded** [comment]
I believe this bug might have already been fixed on prod:

https://github.com/transitland/transitland-datastore/issues/1020

And the import dates for these versions confirm. I'll go ahead and re-import if possible.

**Comment by drewda** [comment]
Closing this since `f-u0j-piemonte~autobus` has been re-imported correctly: https://transit.land/dispatcher/feed-versions/6775a7d7c9edb7254e6fb0fb115884d0038abff2

Work on `f-u-nl` can continue under #27
