### ISSUE TITLE
Refactor and Optimize RSP Distance Calculation

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland#23]

**Comment by doublestranded** [comment]
- [ ]  Add distances array attribute to Route Stop Pattern model
- [ ] Move distance calculation closer to RSP generation and out of SSP import (but still maintain SSP distance attributes)
- [ ] when stops are submitted as changeset, their corresponding Route Stop Patterns must recalculate distances
- [ ] Profile distance calculation (pain point probably in outlier calculation, but we need to be sure)

**Comment by drewda** [comment]
@doublestranded please move this issue over to the `transitland/transitland-datastore` repo
