### ISSUE TITLE
Chennai, India, feed "f-tf34-metropolitantransportcorporation" won't fetch and it's hosted on GitHub

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#232]
https://transit.land/dispatcher/feeds/f-tf34-metropolitantransportcorporation

The system is still pulling an older feed from 7 years ago, and it won't fetch the GitHub/Transitland-hosted feed.

**Comment by irees** [comment]
try:
https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/blob/master/mtc_chennai.zip?raw=true#mtc_chennai
