### ISSUE TITLE
Let's delete feed records for feeds that don't exist anymore

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#233]
Feeds that never existed:
- [f-u0nj1-mtt](https://transit.land/dispatcher/feeds/f-u0nj1-mtt)
- [f-u0r27-societacooperativatrasportibormio](https://transit.land/dispatcher/feeds/f-u0r27-societacooperativatrasportibormio)

Feeds that existed a long time ago, but haven't found new URLs in six months:
- [f-u0n5w-malpensa~shuttle](https://transit.land/dispatcher/feeds/f-u0n5w-malpensa~shuttle)
- [f-u905-lublin](https://transit.land/dispatcher/feeds/f-u905-lublin)
- [f-9z70-lincolnstartran](https://transit.land/dispatcher/feeds/f-9z70-lincolnstartran)

**Comment by irees** [comment]
We can delete the never-imported feeds hosted from Google Drive urls: 
f-u0nj1-mtt
f-u0r27-societacooperativatrasportibormio

Imported feeds that are outdated should stay:
f-u905-lublin
f-9z70-lincolnstartran
f-u0n5w-malpensa~shuttle (although perhaps unset the url, do not link to Drive/Dropbox/etc hosted files)

**Comment by stevevance** [comment]
@irees How do you unset a URL? I thought any `createUpdate` change to a feed had to include a URL. 

----
Destroyed:
f-u0nj1-mtt
f-u0r27-societacooperativatrasportibormio

**Comment by irees** [comment]
There's no way to unset a url (that was a speculative idea on my part) but we should establish a tag for outdated feeds preserved for historical interest.

**Comment by irees** [comment]
Current Feed tags are:

"demo_feed", "download_page_url", "feed_id", "managed_by", "unstable_url", "schedule_frequencies", "manual_import"

You can propose a new tag to use for outdated feeds.

**Comment by stevevance** [comment]
````
"unreachable" if the server disappears without replacement
"unpublished" if the agency still has a presence but no longer publishes?
"outdated" if still valid URL but hasn’t been updated in ages?
maybe it can be "status" with those as the values
status: active - default
status: unreachable… etc?
````

**Comment by stevevance** [comment]
I added "status: unpublished" [to the feed](https://transit.land/feed-registry/operators/o-9qcbb-cityofloditransit~grapeline) from MJC for Lodi, California, because the server is still there, and the agency is still operating, but the feed has been removed.
