### ISSUE TITLE
Westchester, NY, feed "f-dr7-westchestercountybee~linesystem" won't download from Conveyal platform

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#236]
Feed on Dispatcher: https://transit.land/dispatcher/feeds/f-dr7-westchestercountybee~linesystem

Here's information about the Westchester, NY, feed on the 511NY portal, hosted by Conveyal. 
https://transit-admin.511ny.org/public/feed/e3571abf-0284-4b6d-8a3c-0a9f8dbd8d33

I can't download the feed because it uses a token that expires as soon as you download it.

**Comment by drewda** [comment]
@landonreed can we get access to a stable URL for this feed?

Or, if it's a larger discussion, I'm glad to follow up over e-mail.

**Comment by landonreed** [comment]
Hey @drewda, stable links for NYS feeds can be found here: https://www.511ny.org/developers/resources.  For example, Westchester can be found at https://s3.amazonaws.com/datatools-nysdot/public/Westchester_County_Bee-Line_System.zip

**Comment by drewda** [comment]
@landonreed thank you!

@stevevance after you've updated the URL for Westchester, please also add any other NYS feeds that aren't already in the Feed Registry.
