### ISSUE TITLE
sending follow-up e-mails to contributors

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#24]
Currently the Datastore back-end sends automated e-mail notifications to contributors when they create a changeset and when the changeset is applied. But there are an increasing number of times when we want to follow up with a contributor at a different point in the process. Perhaps we should add in functionality to the Dispatcher front-end and the Datastore back-end that would allow us to send a custom e-mail at any time, from `hello@transit.land` with the appropriate template wrapping.

TODO:
- [ ] add an authenticated API endpoint to the Datastore that can send the e-mail through Mandrill (probably wrap this in a gem under `./components/`, so it's not part of Datastore proper)
- [ ] add a form in Dispatcher front-end

Timeframe: Not urgent

//cc @rmglennon @stevevance

**Comment by stevevance** [comment]
What would be even better is to combine multiple emails into a single "digest". 
When I approve changesets I made, I get these emails. Sometimes I'll get 30 each day!

**Comment by drewda** [comment]
@stevevance we do have an internal way to turn off all e-mail notifications. I just did this to your user account. If you'd ever like it turned back on, let me know.

**Comment by drewda** [comment]
This hasn't been necessary. We've had other ways to reach out to feed submitters.
