### ISSUE TITLE
Bologna and Ferrara feeds point to same existing entry in the Feed Registry

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#244]
The separate feeds for Bologna and Ferrara, Italy, point to the same existing feed for Bologna, and thus I cannot submit the Ferrara feed. 

Bologna:
https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsbo&version=20170125&format=zip
This is an existing feed in the [Feed Registry](https://transit.land/feed-registry/operators/o-srb-tperspa), and the feed OnestopID is `f-srb-tperspa`. 

Ferrara:
https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsfe&version=20170125&format=zip

What happened is that someone submitted the Ferrara feed, and although it most likely warned them that they were submitting changes to an existing feed, they changed the city name to Ferrara. When I saw it in the dispatcher, it looked like they were changing Bologna to Ferrara; that would have been incorrect, so I deleted the changeset. 

[I recreated the changeset here](https://transit.land/dispatcher/changesets/6247). I can't use the Feed Registry to submit the Ferrara feed.

**Comment by irees** [comment]
## BO

https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsbo&version=20170125&format=zip
redirect ->
https://solweb.tper.it/resources/files/opendata/gommagtfsbo_20170125.zip

shasum is `1d6833ba198d1189fb7019e3c16945294aa3d070`:
existing FeedVersion http://transit.land/api/v1/feed_versions/1d6833ba198d1189fb7019e3c16945294aa3d070
existing Feed http://transit.land/api/v1/feeds/f-srb-tperspa

agency.txt
```
agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
"TPERBO","TPER spa","www.tper.it","Europe/Rome","it","051 290290"
```

## FE

https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsfe&version=20170125&format=zip
redirect ->
https://solweb.tper.it/resources/files/opendata/gommagtfsfe_20170125.zip

This is a new file that doesn't map to an existing Feed or FeedVersion.

agency.txt
```
agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
"TPERFE","TPER spa","www.tper.it","Europe/Rome","it","051 290290"
```

## Recommendation

Create a new Feed for Ferrera.

Question: Is TPER the same company providing service in both Ferrara and Bologna? If so, map the agency from both feeds to `o-srb-tperspa` and set the operator metro to something broader. If they are separate operators, create a new TPER operator for Ferrara.

**Comment by stevevance** [comment]
New feed created that points to existing TPER operator: https://transit.land/dispatcher/feeds/f-srb-tperspa~ferrara

**Comment by stevevance** [comment]
I don't know how this happened, but there are two feeds that are the same. 

`f-srb-tperspa~bologna`
`f-srb-tperspa`

The `f-srb-tperspa` feed was "deactivated" by removing all operators from it. However, it still generates import errors because, well, no operators could be found!

`f-srb-tperspa` has a bunch of different feed versions than the active `f-srb-tperspa~bologna` feed, so can they be moved from `f-srb-tperspa` to `f-srb-tperspa~bologna`? @irees

**Comment by irees** [comment]
```
feed_dest = Feed.find_by_onestop_id!('f-srb-tperspa~bologna')
feed_orig = Feed.find_by_onestop_id!('f-srb-tperspa')
feed_orig.feed_versions.each do |fv|
  puts fv.sha1
  puts "Updating FeedVersion"
  puts fv.update!(feed_id: feed_dest.id)
  puts "Updating Changesets"
  puts Changeset.where(feed_version_id: fv.id).update_all(feed_id: feed_dest.id)
  puts "Updating EIFF"
  puts EntityImportedFromFeed.where(feed_version_id: fv.id).update_all(feed_id: feed_dest.id)
  puts "Updating SSP"
  puts ScheduleStopPair.where(feed_version_id: fv.id).update_all(feed_id: feed_dest.id)
end; 0

```

**Comment by stevevance** [comment]
Thanks! `f-srb-tperspa` has now been deleted.
