### ISSUE TITLE
RouteToStopPattern algorithm available somewhere ?

### ISSUE THREAD

**Issue by christopheblin** [transitland/transitland#247]
Hi,

I'd like to know if the algorithm describes in https://transit.land/documentation/datastore/routes-and-route-stop-patterns.html can be found in the sources somewhere.

Thanks for your time

**Comment by drewda** [comment]
Thanks for your interest, @christopheblin.

Yes, all Transitland code is open-source. Have a look at:
- https://github.com/transitland/transitland-datastore/blob/master/app/models/route_stop_pattern.rb#L135-L160
- https://github.com/transitland/transitland-datastore/blob/master/app/services/geometry.rb

**Comment by christopheblin** [comment]
Thanks @drewda, I really appreciate your fast and accurate answer !

Seems there are lots of people struggling with the shapes of GTFS (of public transit in general)
 * to generate shapes when they are missing like 
    ** https://github.com/atlregional/bus-router 
    ** http://geops.de/blog/mapping-public-transit-networks?language=en
 * to generate not overlapping shapes
   ** https://medium.com/transit-app/how-we-built-the-worlds-prettiest-auto-generated-transit-maps-12d0c6fa502f
 * to deduce segments
   ** this issue
   ** opentripplanner
   ** me :)

I did not think it was so complicated but now I realize that the journey will be long :)

**Comment by drewda** [comment]
Yes, route geometries are quite a challenge. @doublestranded put a lot of work into Transitland's approach.

If you haven't already, do have a look at the GTFS Best Practices guide: http://gtfs.org/best-practices/ It includes advice for data producers on `shapes.txt` and on how to best represent routes with loops, lassos, and branches.
