### ISSUE TITLE
Confusion about the current f-9v6-capitalmetro feed

### ISSUE THREAD

**Issue by ethanpooley** [transitland/transitland#249]
My understanding was that the appropriate current version of a feed could be reliably identified by looking through the feed versions at https://transit.land/api/v1/feed_versions?feed_onestop_id=f-9v6-capitalmetro for `is_active_feed_version: true`. However, as of about 8pm GMT on 5 June 2017, the "active" version for `f-9v6-capitalmetro` is one that expired two days ago:

![screenshot from 2017-06-05 12-37-15](https://cloud.githubusercontent.com/assets/856884/26800604/c72769c2-49ee-11e7-86a1-f940f3a2c374.png)

The latest version mentioned at the feed_versions endpoint is this one:

![screenshot from 2017-06-05 12-39-35](https://cloud.githubusercontent.com/assets/856884/26800652/fee4ff82-49ee-11e7-890b-314269ab8ed1.png)

The actual best current version is available via the "Fetched from URL" link shown at https://transit.land/feed-registry/operators/o-9v6-capitalmetro, which it says Transitland hit on June 4:

![screenshot from 2017-06-05 12-43-11](https://cloud.githubusercontent.com/assets/856884/26800690/133d2eb4-49ef-11e7-8eaf-ff0476bc977e.png)

What gives? And what is the best approach for a developer to consistently query the datastore for the best current feed?

**Comment by drewda** [comment]
@ethanpooley thanks for your interest.

`is_active_feed_version` is used to indicate the latest version of a feed whose contents have been imported into the Datastore. `ScheduleStopPair`s are only available for the version that is flagged as active.

If you just want to access the most recently fetched version of a feed, you can:

- query for the `FeedVersion` record: https://transit.land/api/v1/feed_versions?feed_onestop_id=f-9v6-capitalmetro&per_page=1&sort_by=fetched_at&sort_order=desc
- download the a copy of the feed version archive: https://transit.land/api/v1/feeds/f-9v6-capitalmetro/download_latest_feed_version

Please reopen this issue if you have any further questions.

We'll work on making this more understandable in docs.

**Comment by ethanpooley** [comment]
That makes sense (now). Thank you! I've adjusted our code and it's working well.
