### ISSUE TITLE
Feeds with the error "undefined method downcase"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#251]
- [ACV bus in Italy](https://transit.land/dispatcher/feed-versions/2db913a8b21f3ea138e3badf41a0e8f1b2be60de) - `f-srb0-autolineechiantivaldarno`
- ~~[ATAF Linea in Italy](https://transit.land/dispatcher/feed-versions/6a9f39d2510ea30f382b3df4f701b97dd8896ad8) as of Mon Jun 26 2017~~

**Comment by stevevance** [comment]
ATAF Linea resolved itself as of Fri Jul 07 2017 13:22:31 GMT-0500 (CDT)
ACV is still broken as of Mon Jul 10 2017 23:49:29 GMT-0500 (CDT)

**Comment by stevevance** [comment]
@irees Any progress on fixing ACV?

**Comment by irees** [comment]
ACV self-resolved. Closing issue.

https://transit.land/dispatcher/feed-versions/0eb1cf30e501bfe7fd1e93bfb8630b491f84522a

**Comment by stevevance** [comment]
Still waiting for it to import (the last import was in June).
