### ISSUE TITLE
Feeds with the error "undefined method pclink"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#252]
- [Go CARTA, Chattanooga](https://transit.land/dispatcher/feed-versions/9c4879ec7bf50ea65aa053d60a50c4963f47a386) as of Thu Jul 13 2017 - `f-dn5r-carta`
- Las Palmas de Gran Canaria in Spain (resolved as of Aug 1 2017)

**Comment by stevevance** [comment]
@irees I added three new feeds, all from MTA in NYC

**Comment by drewda** [comment]
I get a similar error:

```ruby
undefined method `pclink' for nil:NilClass
from /Users/drew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/gtfs-871f27f42ca6/lib/gtfs/source.rb:187:in `block in load_graph'
```

when trying to run FeedInfo on the Amazon SLU shuttle: https://sea-shuttles.com/gtfs.zip

**Comment by stevevance** [comment]
@drewda I spotted that feed elsewhere before seeing your comment and I made this issue for that feed: #269

**Comment by irees** [comment]
In the case of the Seattle shuttles, It's an issue with a `stop_times.txt` table having two rows in the same trip with the same stop_sequence. Looking for a quick fix.

**Comment by irees** [comment]
The Seattle shuttle issue is separate from the `pclink` issue; the feed has many issues/errors beyond this.

**Comment by irees** [comment]
The CARTO feed also had an integrity issue; some trips referenced routes that did not exist. Fixed in the gtfs wrapper and one place in schedule importing.

See: https://github.com/transitland/transitland-datastore/pull/1153

Testing now; will close when done.

**Comment by stevevance** [comment]
The feed should be imported very soon. The last time was August 7. 
https://transit.land/dispatcher/feed-versions/9c4879ec7bf50ea65aa053d60a50c4963f47a386

**Comment by irees** [comment]
The CARTA feed is now importing cleanly.
