### ISSUE TITLE
Feature request: Add GTFS agency ID on the Feed Registry submission page

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#253]
Adding the GTFS agency ID to the Feed Registry "Add new feed" page will help me know which operators I have and don't have in the datastore. Often, operators have the same name and I don't know which one I'm editing. 

The additional info would go on this page https://transit.land/feed-registry/feeds/new/add-operator
<img width="537" alt="pasted_image_6_12_17__17_26" src="https://user-images.githubusercontent.com/1330459/27058021-5e06e25a-4f94-11e7-8dc0-0f03f36932c5.png">

**Comment by drewda** [comment]
@stevevance this is more information than most users need to see in Feed Registry.

But for you, I'd recommend install the Ember Inspector add-on [for Chrome](http://localhost:8000/routing/index-internal.html) or [for Firefox](https://addons.mozilla.org/en-US/firefox/addon/ember-inspector/). Open that, click to the "data" tab, and then you can view all information available on the operator records that are stored locally by the Feed Registry web app.

(FYI, Ember is the JavaScript framework that Feed Registry uses.)
