### ISSUE TITLE
Update GTFS URL for Ruter feed in Norway

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#258]
Support request (see Desk 708) regarding updating the URL for Ruter.

https://transit.land/feed-registry/operators/o-u4x-ruter

all references to http://reis.ruter.no/gtfs/gtfs.zip need to be removed. 

Only references to https://github.com/RuterNo/open-data/blob/master/gtfs.zip?raw=true are to be kept. 

Some files were incorrectly updated on that GitHub site, but this has been corrected. Second reply:

"Actually, I started the process of changing the feed URL the way you mention, by pressing “Edit feed and operator details”. However, because of another agency model in the new feed, the new agencies (one agency for each transport mode) were added, but the old feed wasn’t replaced. So I guess the best would be for you to delete https://transit.land/feed-registry/operators/o-u4x-ruter manually."

**Comment by stevevance** [comment]
"Feed 1"
The other feed `http://reis.ruter.no/gtfs/gtfs.zip` has onestop ID`f-u4-ruter~flybussen~stfoldkollektivtrafikk~hedmarktrafikk~oppla` and supplies these operators:

- o-u4x-ruter (A)
- o-u4x-stfoldkollektivtrafikk (Ø)
- o-u6-hedmarktrafikk (H)
- o-u4-opplandstrafikk (L)
- o-u4w-brakar (B)

"Feed 2"
The feed `https://github.com/RuterNo/open-data/blob/master/gtfs.zip?raw=true` has the onestop ID of `f-u-ruterbuss~ruterbåt~rutertrikk~rutertbane~buss~tog~båt~flytog` and is supplying the following operators:

- o-u4x-ruterbuss (RB)
- o-u4x-ruterbåt (RF)
- o-u4xs-rutertrikk (RS)
- o-u4xs-rutertbane (RT)
- o-u-buss (BB)
- o-u4-tog (TT)
- o-u4-båt (FF)
- o-u4x-flytog (FT)
- o-u4x-flybuss (FB)

Does Feed 2 supply all of the operators in Feed 1?
