### ISSUE TITLE
Bus Pastel in France won't fetch "f-u0f7d-pastelmavilleestbelle"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#259]
**France**
- Dispatcher: [f-u0f7d-pastelmavilleestbelle](https://transit.land/dispatcher/feeds/f-u0f7d-pastelmavilleestbelle)
- URL: http://www.buspastel.fr/google_transit.zip
- [Feed fetch issue](https://transit.land/dispatcher/issues/feed-fetch/1003366): 

**CARTA**
- Dispatcher: [f-dn5r-carta](http://www.gocarta.org/developers/GTFS.zip)
- URL: http://www.gocarta.org/developers/GTFS.zip
- [Feed fetch issue](https://transit.land/dispatcher/issues/feed-fetch/1140099)

````
GTFS::InvalidSourceException /home/deploy/.bundler/transitland/ruby/2.3.0/bundler/gems/gtfs-e3a78cb57767/lib/gtfs/source.rb:44:in `initialize' ...
````

**Comment by stevevance** [comment]
It looks like the feed is missing `shapes.txt`.

**Comment by stevevance** [comment]
The Pastel Ma Ville est Belle feed issue has been resolved.

**Comment by stevevance** [comment]
@irees This feed has become a problem again. All six required GTFS files are there, but Dispatcher reports `GTFS::InvalidSourceException` on [this feed fetch issue](https://transit.land/dispatcher/issues/feed-fetch/1290645).

**Comment by irees** [comment]
@stevevance the feed is now in a folder inside the zip; the url will need to be updated to:

http://buspastel.fr/google_transit.zip#google_transit
