### ISSUE TITLE
Bogotá, Colombia, ZIP file appears to be corrupt

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#264]
This is the [long URL](https://doc-0k-94-docs.googleusercontent.com/docs/securesc/e89rs9so41v2pl624063l3d6rgih7jr3/p7hdimb6e08cflt22nklhj2vuknsa8gj/1499990400000/15277077861489136863/10593479090703137318/0Bzyr0SveNi4AYXdDS1RHNi1ueUE?e=download&nonce=7j38o7lg93d9o&user=10593479090703137318&hash=imileku2q54nkpsipb84okpgep09mjvg) for the Google Drive-hosted ZIP file. The URL is found in [this G Drive directory](https://drive.google.com/drive/folders/0Bzyr0SveNi4Ab2p4V1FtNGVYZ1U), which I found in a link in a menu on [Colombia government page](http://www.simur.gov.co/gtfs). 

Feed Registry says that this ZIP file appears to be corrupt, although I can open it on my computer. 

The URL to the same G Drive file might change, [here's the latest one I tried](https://doc-0k-94-docs.googleusercontent.com/docs/securesc/e89rs9so41v2pl624063l3d6rgih7jr3/45vn19q8d5romvuori1m2jlpscnohj6m/1504108800000/15277077861489136863/10593479090703137318/0Bzyr0SveNi4AYXdDS1RHNi1ueUE?e=download&nonce=03njhfgoc5cpg&user=10593479090703137318&hash=vjbbflp9lcpkjaotv51fnvhrtc50s4cv) (8/30/17)

**Comment by rmglennon** [comment]
A user requested we add this feed and sent this Google Drive link through support email, too (see Desk 930).

**Comment by stevevance** [comment]
@rmglennon Was it the same link?

**Comment by rmglennon** [comment]
@stevevance yes - https://drive.google.com/drive/folders/0Bzyr0SveNi4Ab2p4V1FtNGVYZ1U

**Comment by irees** [comment]
@stevevance The currently posted file is valid GTFS. However, I don't think it is currently possible to get a Google Drive direct download url that will work with Transitland; the links always return html/javascript, requiring a browser to complete the download.

One option is to copy the feed to https://github.com/transitland/gtfs-archives-not-hosted-elsewhere or create the feed manually and then upload the file through dispatcher.

**Comment by stevevance** [comment]
Bogotá is now in Feed Registry, and is currently being imported. 

I downloaded it from Google Drive, hosted it on our GitHub repo, and submitted it to Feed Registry. For new versions I may either upload it to GitHub or upload it through Dispatcher. 

The current version has a service date through December 2020, but @rmglennon can you ask if they have a newer version? (The file on Drive was last updated in June 2017.)

**Comment by rmglennon** [comment]
That's great, @stevevance! I can check, but I think the user just found the link and may not actually be involved in the feed creation.
