### ISSUE TITLE
SFMTA "f-9q8y-sfmta" SSL certificate expired

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#266]
The San Francisco MTA feed [f-9q8y-sfmta](https://transit.land/dispatcher/feeds/f-9q8y-sfmta) has an expired SSL certificate. 

Yes, the SFMTA’s SSL cert is bad
expired 7 days ago
the current data is good through Aug 10 - hopefully they can fix their SSL cert before that
Non-SSL url http://archives.sfmta.com/transitdata/google_transit.zip redirects to https://gtfs.sfmta.com/transitdata/google_transit.zip

**Comment by drewda** [comment]
Worst case, we'll `wget https://gtfs.sfmta.com/transitdata/google_transit.zip --no-check-certificate` and then manually upload a new feed version (using the new functionality introduced in https://github.com/transitland/transitland-datastore/issues/1125 and https://github.com/transitland/dispatcher/pull/247).

**Comment by kuanb** [comment]
Piggy backing on this, is there a way to log defunct URLs?

E.g. API call http://transit.land/api/v1/feeds?onestop_id=f-dqcjr-dccirculator indicates that DC Circulator GTFS feed should be available at http://circulatordashboard.dc.gov/circulatordata/gtfs/gtfs.zip which leads to a 404 page.

**Comment by drewda** [comment]
@kuanb FYI, when the fetch process runs daily it creates "issues" for any feed that can't be successfully fetched. Here's a view of feeds that have had fetch issues most recently: https://transit.land/dispatcher/feeds?latest_fetch_exception=true

@stevevance regularly checks this list and updates broken URLs, when it's possible to find a new working equivalent.

Kuan, if you want to help fix any broken feeds, please do feel free to open issues on this repo with as all the relevant info and also tag Steven.

**Comment by stevevance** [comment]
@kuanb For info on the DC Circulator issue, see #268

**Comment by kuanb** [comment]
Awesome thanks

**Comment by stevevance** [comment]
@drewda @irees I tried uploading a new feed version for SFMTA, uploading the ZIP file that I downloaded with Safari. 

Dispatcher displays this complaint:

````
Error uploading feed version: {"readyState":4,"then":null,"responseText":"&lt;html&gt;\r\n&lt;head&gt;&lt;title&gt;413 Request Entity Too Large&lt;/title&gt;&lt;/head&gt;\r\n&lt;body bgcolor=\"white\"&gt;\r\n&lt;center&gt;&lt;h1&gt;413 Request Entity Too Large&lt;/h1&gt;&lt;/center&gt;\r\n&lt;hr&gt;&lt;center&gt;nginx/1.4.6 (Ubuntu)&lt;/center&gt;\r\n&lt;/body&gt;\r\n&lt;/html&gt;\r\n","status":413,"statusText":"Request Entity Too Large","errorThrown":{"line":72,"column":27634,"sourceURL":"https://d11xhlzkgsq6oc.cloudfront.net/dispatcher/assets/vendor-1835728482bd99593e163332e1c7e719.js"}}
````

**Comment by drewda** [comment]
@irees increased the upload limit on production server config (https://github.com/mapzen/opsworks-transitland/commit/9c163773fdecddd03e70a1a6a02cca66489e6d6b) -- so not sure why there would be size limit errors. Perhaps not all nodes have the updated config?

**Comment by irees** [comment]
@drewda hm - the stack settings are updated, and I did a deploy - I will check with ops.

**Comment by stevevance** [comment]
@irees @drewda The error occurs immediately - before the file has a chance to be uploaded. Might the browser be reporting the wrong file size, or throwing the error?

**Comment by drewda** [comment]
@stevevance still not sure why the public-facing web servers aren't accepting those file sizes. @irees will have to investigate further.

In the meantime, it's possible to upload directly to one of the internal web servers, bypassing the external limits. I just did this for the latest SFMTA feed by doing:

```sh
curl -v  -H "Authorization: Bearer TOKEN_COPIED_FROM_WEB_BROWSER" -H 'Content-Type: multipart/form-data' -F "feed_version[feed_onestop_id]=f-9q8y-sfmta" -F "feed_version[file]=@sfmta.zip" http://54.144.84.97/api/v1/feed_versions
```

**Comment by stevevance** [comment]
Another feed has an SSL problem #280

**Comment by drewda** [comment]
SFMTA feed appears to fetch successfully now.
