### ISSUE TITLE
Torrance, California, "f-9q5b-torrancetransit" demo feed has gone missing

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#267]
https://transit.land/dispatcher/feeds/f-9q5b-torrancetransit - this feed is a "demo feed"

http://www.torranceca.gov/TransitFeed/google_transit.zip

It looks like the city launched a brand-new website.

**Comment by drewda** [comment]
resolved by https://transit.land/dispatcher/changesets/7017
