### ISSUE TITLE
Disassociate DC Circulator operator from the broken DC Circulator feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#268]
The DC Circulator appeared in the dispatcher as a feed with a problem just yesterday. The DCC is fed by its own feed, and the [WMATA feed](https://transit.land/feed-registry/operators/o-dqc-met), although each describes the DCC routes differently. 

I'm going to disassociate the [DCC feed record](https://transit.land/dispatcher/feeds/f-dqcjr-dccirculator) from the [DCC operator record](https://transit.land/feed-registry/operators/o-dqcjr-dccirculator) so that the DCC operator is fed only by the WMATA feed. If the DCC feed reappears then I can re-associate the DCC feed and operator records. 

I applied this changeset, but it didn't work, and the feed and operator are still associated. 

````
{
    "changes": [
        {
            "action": "createUpdate",
            "feed": {
                "onestopId": "f-dqcjr-dccirculator",
                "url": "http://circulatordashboard.dc.gov/circulatordata/gtfs/gtfs.zip",
                "doesNotIncludeOperators": [
                    {
                        "operatorOnestopId": "o-dqcjr-dccirculator",
                        "gtfsAgencyId": ""
                    }
                ]
            }
        }
    ]
}
````

**Comment by irees** [comment]
in this case gtfs_agency_id was null, not an empty string... fix applied in https://transit.land/dispatcher/changesets/7016

**Comment by stevevance** [comment]
@irees how do I know when the string is empty versus when it's null?
