### ISSUE TITLE
Feed for Downtown Alliance shuttle in NYC "f-dr5re-downtownalliance" has gone missing

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#270]
Info:
- Name: Downtown Alliance (Connection)
- Location: New York City
- Dispatcher (operator): https://transit.land/dispatcher/operators/o-dr5re-downtownalliance
- Dispatcher (feed): https://transit.land/dispatcher/feeds/f-dr5re-downtownalliance
- Feed Registry: https://transit.land/feed-registry/operators/o-dr5re-downtownalliance
- Feed URL: http://mjcaction.com/MJC_GTFS_Public/downtown_nyc_google_transit.zip

I am adding the tag "status=unreachable" for now. The feed is hosted by MJC, which we have a contact for.

**Comment by drewda** [comment]
@stevevance looks like this has now fetched successfully. Please remove the `status` tag and close this issue.
