### ISSUE TITLE
Feed for Sarasota County "f-dhv-sarasotacountyareatransit" has gone missing

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#271]
Info:
- Name: Sarasota County Area Transit (SCAT)
- Location: Sarasota County, Florida
- Dispatcher (operator): https://transit.land/dispatcher/operators/o-dhv-sarasotacountyareatransit
- Dispatcher (feed): https://transit.land/dispatcher/feeds/f-dhv-sarasotacountyareatransit
- Feed Registry: https://transit.land/feed-registry/operators/o-dhv-sarasotacountyareatransit
- Feed URL: https://www.scgov.net/SCAT/Google/sarasotacounty-fl-us2016Nov.zip

I am adding the tag "status=unreachable" for now. 
I've asked the agency on Twitter if they have a new URL.

**Comment by irees** [comment]
Closing issue. If a new url becomes available, we can update the feed and remove the `status: unreachable` tag.
