### ISSUE TITLE
Feeds with the issue "undefined method `to_seconds' for nil:NilClass"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#275]
````
undefined method `to_seconds' for nil:NilClass
Did you mean?  to_json
````

**Feeds**
- City of Commerce municipal bus lines - [f-9q5c-cityofcommercemunicipalbuslines](https://transit.land/dispatcher/feeds/f-9q5c-cityofcommercemunicipalbuslines) - [import log](https://transit.land/dispatcher/feed-versions/faac5a1e92473d09e0cb2da9d6e5d4c3255864bf)
- Amazon South Lake Union Seattle shuttle - [f-c23n-welcometoamazonslushuttle](https://transit.land/dispatcher/feed-versions/2546072dcc1fc2b7666149f701900a13026616c7)

**Comment by irees** [comment]
This is tricky because the feed violates the stop_times.txt spec. I may add a meaningful exception, but there's no obvious fix.

**Comment by irees** [comment]
https://developers.google.com/transit/gtfs/reference/stop_times-file

> You must specify arrival and departure times for the first and last stops in a trip.

**Comment by irees** [comment]
I added a catch to log & skip any trips with invalid stop_times.

https://github.com/transitland/transitland-datastore/pull/1163
