### ISSUE TITLE
Feeds with error "undefined method id"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#276]
- Rhode Island Public Transit Authority "f-drm-rhodeislandpublictransitauthority" - [Feed version error](https://transit.land/dispatcher/feed-versions/cbe56f9d63ba0c159ea311883aa391ff8e58b333)

````
undefined method `id' for nil:NilClass
````

**Comment by irees** [comment]
Imported clean on Sep 10. https://transit.land/dispatcher/feed-versions/4dc7852f3b028deb4fa87e82dec93aae2bdcf49d
