### ISSUE TITLE
Delete "Eugene to Bend" Oregon because it's a subset of another feed

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#283]
**Keep**
https://transit.land/feed-registry/operators/o-9rb-pacificcrestlines which is fed by `f-9rb-pacificcrest~or~us`

**Destroy**
https://transit.land/feed-registry/operators/o-9rc-eugenetobend which is fed by `f-9rc-eugenetobend~or~us` (this feed is also outdated by nearly a year)

The Keep feed already includes the data in the Destroy feed.

**Comment by stevevance** [comment]
@irees Can you review this and approve this plan?

**Comment by irees** [comment]
Removed `o-9rc-eugenetobend` with changeset `9021`
