### ISSUE TITLE
problems using NYC bus schedules in transitflow.py

### ISSUE THREAD

**Issue by joshdelarosa1** [transitland/transitland#286]
While the subway GTFS files are in the database, the NYC bus GTFS are not currently in the feed database.

In NYC, the MTA separates the [subway](http://web.mta.info/developers/data/nyct/subway/google_transit.zip) feed from it's bus feeds. Below are the five feeds missing from the NYC system:

1. [Bronx](http://web.mta.info/developers/data/nyct/bus/google_transit_bronx.zip)
2. [Brooklyn](http://web.mta.info/developers/data/nyct/bus/google_transit_brooklyn.zip)
3. [Queens](http://web.mta.info/developers/data/nyct/bus/google_transit_queens.zip)
4. [Manhattan ](http://web.mta.info/developers/data/nyct/bus/google_transit_manhattan.zip)
5. [Staten Island](http://web.mta.info/developers/data/nyct/bus/google_transit_staten_island.zip)

Also, I was unable to register these feeds. I'll open up a separate issue for that problem.

**Comment by irees** [comment]
Hi @joshdelarosa1 

All the NYC MTA feeds are in the registry:

https://transit.land/feed-registry/operators/o-dr5r-nyct

- which is a single operator composed from the subway and bus feeds for Manhattan, Bronx, Brooklyn, Queens, Staten Island, and the Bus Company.

We also have LIRR & Metro-North:

https://transit.land/feed-registry/operators/o-dr7-metro~northrailroad
https://transit.land/feed-registry/operators/o-dr7-metro~northrailroad

**Comment by joshdelarosa1** [comment]
In lower Manhattan as an example, only the Downtown Connection busses are pulled into the [animation](https://vimeo.com/231957819). 

In the outer boroughs, only the Nassau county buses are pulled in by the API. I've tried different bounding boxes with no success. Is this an transit animation issue instead? Judging by the routes, I don't think the subways were recoded as buses.

**Comment by irees** [comment]
@joshdelarosa1 can you provide the command line arguments you used?

**Comment by irees** [comment]
@joshdelarosa1 ah - it looks like we switched over to the newest versions of many of the MTA feeds this morning, which only includes service from 2017-09-01 onwards. Try using next Tuesday, 2017-09-05 as the --date argument.

**Comment by joshdelarosa1** [comment]
I tried several different bounding boxes, including:

` python transitflow.py --name=lwr_nyc --bbox=-74.028518,40.695932,-73.987684,40.709385 --clip_to_bbox`
and 
`python transitflow.py --name=lwr_nyc --bbox=-74.553909,40.424474,-73.247223,40.855371 --clip_to_bbox`

I also tried with and without `--clip_to_bbox`

**Comment by irees** [comment]
(apologies for the inconvenience - the process that converts the data to routable graph tiles runs twice per week and sometimes we import data slightly early to accommodate this timeline)

**Comment by joshdelarosa1** [comment]
I tried a Sunday (9/17/17) and it worked. But a Monday with ferry service brought a new error message.  I wonder if it's related to the size of the file. 

`python transitflow.py --name=nyct2 --date=2017-09-18 --apikey=mapzen-<key> --operator=o-dr5r-nyct,o-dr5r-nycferry`

Traceback (most recent call last):
  File "transitflow.py", line 372, in <module>
    results, failures = animate_operators(operators, DATE)
  File "transitflow.py", line 189, in animate_operators
    output = animate_one_day(i, date)
  File "transitflow.py", line 169, in animate_one_day
    origin_times, destination_times, origin_stops, destination_stops, route_ids = get_schedule_stop_pairs(operator_onestop_id, date)
  File "transitflow.py", line 63, in get_schedule_stop_pairs
    for i in ssp_request:
  File "/Users/josuedelarosa/dev/transitland-processing-animation-master/transitflow/transitland_api.py", line 61, in request
    data = self._request(next_uri)
  File "/Users/josuedelarosa/dev/transitland-processing-animation-master/transitflow/transitland_api.py", line 42, in _request
    data = json.loads(response.read())
  File "/Users/josuedelarosa/anaconda/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/Users/josuedelarosa/anaconda/lib/python2.7/httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "/Users/josuedelarosa/anaconda/lib/python2.7/httplib.py", line 633, in _read_chunked
    value.append(self._safe_read(amt))
  File "/Users/josuedelarosa/anaconda/lib/python2.7/httplib.py", line 690, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(931 bytes read, 7261 more expected)

**Comment by irees** [comment]
hi @jjoshdelarosa1 Can you try it one more time? That might have been a spurious error.

**Comment by joshdelarosa1** [comment]
Hi,

The NYC data extract worked"

`python transitflow.py --name=nyct2 --date=2017-09-18 --apikey=mapzen-<key> --operator=o-dr5r-nyct,o-dr5r-nycferry`

https://vimeo.com/232595376

I tried the DC area again but had a different problem:
`python transitflow.py --name=dc --apikey=mapzen-<key> --bbox=-77.252647,38.729463,-76.831978,39.056878 --exclude=o-9-amtrak,o-9-amtrakcharteredvehicle`

12 operators successfully downloaded.
2 operators failed.
failed operators: ['o-dqc-met', 'o-dqc-marylandtransitadministration']

I think this is isolated to areas with busier transit areas (I had no issues with Central Florida). I'll give it try later.  Otherwise, the program works great.

Thanks for making this available.

**Comment by irees** [comment]
Thanks for using the program :) I am going to mark this issue as closed unless any other issues come up.
