### ISSUE TITLE
Unable to Add NYC Bus Feeds

### ISSUE THREAD

**Issue by joshdelarosa1** [transitland/transitland#287]
Per #286, I was unable to register the NYC MTA bus feeds. The systems says these feeds are duplicates. However, NYC MTA separates the subway feed and the five bus feeds.

![mtafeeds](https://user-images.githubusercontent.com/5900421/29982536-1969b8cc-8f20-11e7-9cc7-ead77d1c4107.PNG)

**Comment by drewda** [comment]
See https://github.com/transitland/transitland/issues/286#issuecomment-326649578 for clarification.
