### ISSUE TITLE
Odd problem with County Connection "f-9q9p-ccctaorg"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#290]
`f-9q9p-ccctaorg` ([dispatcher](https://transit.land/dispatcher/feeds/f-9q9p-ccctaorg')) is a demo feed managed by Trillium. 

**The problem**
- The [most recent feed version](https://transit.land/dispatcher/feed-versions/be995f7d0e68a056955366719be375b6b16a0413) is missing a lot of details, including which URL it represents, and schedule info (first service date, last service date). 
- The most recent feed version has an "import issue" that mentions a completely unrelated feed:
````
No Agency in the GTFS Feed had a matching Transitland Operator Agencies in GTFS Feed: 90000000: Metrorail Western Cape Existing Feed agency_id <-> Transitland Operator associations: : o-9q9p-countyconnection
````

I tried correcting it by fetching it again, and then importing the feed, but nothing changed. 

Did this feed somehow get mixed up with another?

**Comment by irees** [comment]
Looks like this was a broken file that was uploaded via script; I deleted the FeedVersion.
