### ISSUE TITLE
Delete a duplicate County Connector (CCCTA) feed "f-9q9p-ccctaorg"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#291]
The feed `f-9q9p-ccctaorg` (A) duplicates `f-9q9p-countyconnection` (B). 

At one point, feed (A) got mixed up with the same URL as a completely unrelated feed `f-dru-chittendoncounty~vt~us` (C), and (A) was assigned the same feed URL as (C). 

This probably happened because the short name of transit operator in (A) is "CCCTA" and the short name for the transit operator in (C) is "CCTA".

The URL for (A) has been cleared out to prevent any further mixups. 

(A) is not feeding any operators and can be safely deleted. 

````
{
    "changes": [{
        "action": "destroy",
        "feed":  {
            "onestopId": "f-9q9p-ccctaorg"
        }
    }]
}
````

**Comment by irees** [comment]
Feed deleted.
