### ISSUE TITLE
Feed correction: Rename New York City Department of Transportation (NYC DOT) to "Staten Island Ferry"

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#30]
Support request (from @riordan):
Rename New York City Department of Transportation (NYC DOT) to "Staten Island Ferry"

https://transit.land/feed-registry/operators/o-dr5r7-nycdot
It's the Staten Island Ferry

**Comment by drewda** [comment]
In Playground and API, it's possible to access the Staten Island Ferry route by name or location. So the fact that NYC DOT is identified as the agency that operates it doesn't seem like a blocker to people who are unfamiliar with that administrative detail.
