### ISSUE TITLE
GTFS source problem with Jacksonville, FL, feed "f-djmu-jacksonvilletransportationauthority"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#300]
The feed `f-djmu-jacksonvilletransportationauthority` ([Dispatcher](https://transit.land/dispatcher/feeds/f-djmu-jacksonvilletransportationauthority)) for Jacksonville, Florida, threw a `GTFS::InvalidSourceException` [feed fetch error]. 

I downloaded the feed and I'm guessing that two of the filenames are wrong. 

````
stop_times_ALL.txt
stop_times_TimepointsOnly.txt
````
(They have identical file sizes.)

<img width="243" alt="screenshot 2017-10-08 11 33 14" src="https://user-images.githubusercontent.com/1330459/31318750-7d3de92c-ac1c-11e7-96a9-7658cca3e8b4.png">

**Comment by irees** [comment]
We can't automatically try to infer incorrect filenames. Will need to email operator.

**Comment by stevevance** [comment]
The feed resolved the issue itself.
