### ISSUE TITLE
when `feed_id` is present in `feed_info.txt` use that as third component of feed Onestop ID

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#31]
Will involve:

- [x] small additions to GTFS wrapper library
- [x] small additions to Datastore FeedInfo

Some feeds contain a string `feed_id` column in their `feed_info.txt` file. For example:

- TriMet https://developer.trimet.org/gtfs_ext.shtml
- feeds under management by Trillium
- feeds under management by Conveyal

We should make use of this when it's present.

In the future, if `feed_id` becomes more common and there is a mutual enforcement of global uniqueness, we could use these values instead of generating Onestop IDs for feeds.

In the meantime, we should at least use these, when available, as the name component of feed Onestop IDs.

//cc @abyrd @landonreed @antrim

**Comment by abyrd** [comment]
OpenOV in the Netherlands also supplies a feed_id. http://gtfs.openov.nl/gtfs/ 
We have already proposed this extension to GTFS-changes. Just let us know when you're making use of it in Transit Land so we can tell the GTFS changes mailing list we have multiple producers and consumers, then update the GTFS spec.

**Comment by abyrd** [comment]
We decided yesterday that we will be making prominent use of feed IDs in our data tools products, and will probably maintain a mapping for all known feeds that do not yet contain a feed_id. We could somehow maintain this list in a shared way so that we all agree on the feed IDs until data producers start providing them in the feeds.

**Comment by irees** [comment]
@abyrd: Is feed_id case-sensitive?

**Comment by drewda** [comment]
@abyrd thanks for the background info. I'll follow up over e-mail.

We've got this change on our end coming along and will roll out to our production servers in the near future.

**Comment by abyrd** [comment]
@irees I just now saw your comment, sorry for the lag. I think by default feed_id would be case sensitive like all other GTFS IDs. The main restriction is that is cannot contain a colon character ":". This allows us to prefix GTFS entity IDs with a feed_id to make them globally unique (e.g. TriMet:1234)
