### ISSUE TITLE
Too many "route_stop_patterns_by_onestop_id" for routes API. Isit possible to filter the correct pattern ids

### ISSUE THREAD

**Issue by rippll-miles** [transitland/transitland#317]
The below is returning too many "route_stop_patterns_by_onestop_id", there should be 4 however the are duplicates/updated ids.
Is there a way to filter the most recent/correct IDs?

https://transit.land/api/v1/routes?vehicle_type=bus_service&operated_by=o-u33d-berlinerverkehrsbetriebe

`{
"geometry": {
"type": "MultiLineString",
"coordinates": [
[] 29 items,
[] 20 items,
[] 27 items,
[] 18 items
]
},
"onestop_id": "r-u33db-142",
"created_at": "2017-02-18T04:04:38.230Z",
"updated_at": "2017-05-15T16:53:08.495Z",
"tags": {},
"created_or_updated_in_changeset_id": 5914,
"name": "142",
"vehicle_type": "bus_service",
"color": null,
"stops_served_by_route": [],
"operated_by_onestop_id": "o-u33d-berlinerverkehrsbetriebe",
"operated_by_name": "Berliner Verkehrsbetriebe",
"wheelchair_accessible": "unknown",
"bikes_allowed": "unknown",
"route_stop_patterns_by_onestop_id": [
"r-u33db-142-946975-0598e8",
"r-u33db-142-946975-b5ad92",
"r-u33db-142-b5fcb2-816281",
"r-u33db-142-b5381e-ad4105",
"r-u33db-142-b5381e-9fcaf7",
"r-u33db-142-405df2-0ae32c",
"r-u33db-142-a865dc-297886",
"r-u33db-142-fa2c11-7b07ff",
"r-u33db-142-df64e4-e771c5"
]
},`

**Comment by drewda** [comment]
To view the RSPs associated with just that particular route, try http://transit.land/api/v1/route_stop_patterns?traversed_by=r-u33db-142

Can you provide more information on which RSPs you think are accurate and which are not? I am unfamiliar with this feed, so more information would be helpful.

Note that RSPs are unique by both geometry and stop pattern. If you have not already, read the docs at: http://transit.land/documentation/datastore/routes-and-route-stop-patterns.html#route_stop_patterns

**Comment by drewda** [comment]
I now see your email:

> I’m trying to use https://transit.land/api/v1/routes?vehicle_type=bus_service&operated_by=o-u33d-berlinerverkehrsbetriebe
> However its return duplications of route_stop_patterns, they each have unique route_stop_patterns ids however the content of those ids is duplicated. I would expect there to be the same number of route_stop_patterns as co-ordinate arrays. 
> Is there anything that can be done to fix this, its have a severe effect on a live project.

Note that RSPs are unique by both geometry and stop pattern. This means that two RSPs can have the same exact geometry but have a different list of stops they visit. For example, one RSP may represent "skip stop" service: https://en.wikipedia.org/wiki/Skip-stop

I think this should help clarify your questions and your application -- if not feel free to reopen and add more comments!

**Comment by rippll-miles** [comment]
Thanks for your reply for example, the below 2 are dups
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-b5381e-ad4105
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-b5381e-9fcaf7
The below is also the same, however cleaned up as a duplicated stop has been removed
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-405df2-0ae32c

These 2 below are also the same except a duplication of stations has been removed
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-fa2c11-7b07ff
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-a865dc-297886

These 2 below are dups 
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-946975-b5ad92
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-946975-0598e8
With the below being a clean up removing duplicated stations
https://transit.land/api/v1/route_stop_patterns?onestop_id=r-u33db-142-b5fcb2-816281

All of which are the RSPs of route https://transit.land/api/v1/routes?vehicle_type=bus_service&operated_by=o-u33d-berlinerverkehrsbetriebe&onestop_id=r-u33db-142

To your point the majority are unique with the exception of a couple, however there are multiple versions of the same routes with fixes, is there a way to determine the correct/latest routes to use ?

Thanks

**Comment by rippll-miles** [comment]
Below is the URL for the GTFS feed if the dataset needs to be dropped & replaced

https://www.vbb.de/media/download/2029
