### ISSUE TITLE
Nairobi, Kenya feed returns InvalidSourceException

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#32]
When running http://www.digitalmatatus.com/pdf/GTFS_Data.zip through FeedInfo, `InvalidSourceException` is returned.

**Comment by irees** [comment]
A type of 'nested' GTFS data. The CSV files are inside a directory 'GTFS_Data', not in the root of the archive.

**Comment by drewda** [comment]
I'll write to the folks at MIT and see if they can remove the nested directory. If not, https://github.com/transitland/transitland-datastore/issues/316 sounds like a good eventual solution.

**Comment by drewda** [comment]
Sarah Williams pointed us to http://www.digitalmatatus.com/pdf/GTFS_DATA_1.zip instead. That works.
