### ISSUE TITLE
Feed import hangs

### ISSUE THREAD

**Issue by heyarne** [transitland/transitland#321]
Hi!
I'm trying to import https://www.vbb.de/media/download/2029, which is the official GTFS feed for the Verkehrsverbund Berlin Brandenburg (Germany) as per [OpenMobilityData](https://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213).  Unfortunately when trying to import the feed over the web url it just seems to hang indefinitely at 95%. Can I do anything to help debug this?

**Comment by heyarne** [comment]
Consider this solved! It was indeed just a long time it took going from 95% to 100%. :)

**Comment by drewda** [comment]
@heyarne thanks for your patience. (The final portion of processing a large GTFS feed is indeed the most resources intensive.)
