### ISSUE TITLE
feed-registry not loading

### ISSUE THREAD

**Issue by TheMapSmith** [transitland/transitland#324]
Hello! 👋 

Love you, love your service ❤️ 

I'm noticing today that the `/feed-registry` page isn't loading. The web console shows a few errors: 

![image](https://user-images.githubusercontent.com/8357118/69569675-24797880-0f8c-11ea-8938-3be00264bd14.png)

Error text:
`GET https://transit.land/api/v1/operators?country=&import_level=&metro=&name=&offset=0&short_name=&sort_key=name&sort_order=asc&state=&total=true&api_key=` `502`

`Error while processing route: index Adapter operation failed Error: Adapter operation failed`

`Error: Could not find module @ember/controller imported from feed-registry/controllers/object`

**Comment by drewda** [comment]
Thanks for the kind words and for using Transitland!

Our monitoring system has been picking up interruptions for some users of the Transitland Datastore API — including the Feed Registry user interface. We've been working to debug and fix the issue today. Will be posting status updates at https://twitter.com/transitland/

**Comment by drewda** [comment]
Datastore API performance should be back to normal now. Feel free to open a new issue with future issues or contact us by email or Twitter.
