### ISSUE TITLE
Questions regarding accessing route and operator data from feed & discrepancy Datastore V1 and the map

### ISSUE THREAD

**Issue by GitBrum** [transitland/transitland#332]
I am requesting data from Transitland Datastore V1

Let's say I want to analyze all transit of Stockholm (Sweden) operated by SL (onestop_id=o-u6s-sl). I want their routes with corresponding stops (coordinates) and schedules. First I tried to inspect the API endpoint using Postman using my API key and the onestop_id of the operator. Later on I tried the same using Python 3.7 on a Windows 10 64-bit. Both resulted in the same output:

1) Postman generated request: 'https://api.transit.land/api/v1/operators?apikey=XXX&onestop_id=o-u6s-sl'
Output: `{
    "message": "Couldn't find Operator: o-u6s-sl"
}`

Going back to the map, I saw the source feed warned me that: _This operator includes data from the feed record with Onestop ID of f-u-se. See the feed record for Transitland's archive of fetched versions, as well as URLs for accessing the feed._

So I accessed the feed instead of the operator by requesting: 'https://api.transit.land/api/v1/feeds?apikey=XXX&onestop_id=f-u-se'
Output: feed with a dictionary of all operators, but no information about the routes anymore.
and

Second I tried to access the operators routes via the following endpoint. 

2) Postman generated request: 'https://api.transit.land/api/v1/routes?apikey=XXX&operated_by=o-u6s-sl'
Output: `{
    "routes": [],
    "meta": {
        "sort_key": "id",
        "sort_order": "asc",
        "per_page": 50,
        "offset": 0
    }
}`

Hence, my questions, respectively to requests 1) and 2), are: 
1) How can I design my API in such a way that I can access the routes of an operator which is part of a bigger feed?
2) Is all the data presented in the [map ](https://www.transit.land/map#1.5/12.7/-119.5)available for requests in the transitland Datastore V1 or is there a discrepancy in available data?

Thanks in advance!

**Comment by drewda** [comment]
Re 1: you are encountering a known bug in the v1 Datastore API. This is resolved in the v2 REST APIs, which will be publicly available soon. Thanks for your patience.

Re 2: the map is powered by the v2 Vector Tiles (which bypass the v1 Datastore API and its limitations). If you want to try using these tiles yourself, see https://www.transit.land/documentation/vector-tiles

**Comment by GitBrum** [comment]
1) I am looking forward:)

2) Using the same example for Stockholm and an arbitrary route (onestop_id=r-u6sce-69) I tried the following endpoint to access the v2 Vector Tiles (again using Postman to inspect the endpoints).

`https://transit.land/api/v2/tiles/routes/tiles/{z}/{x}/{y}.pbf?apikey=XXX&onestop_id=r-u6sce-69`
which gave me the error: 'invalid tile coordinates'

I assume x,y,z are the tile coordinates so I looked them for for the same example above using [missinglink ](http://missinglink.github.io/leaflet-spatial-prefix-tree/). As a result I tried the following enpoint:

'https://transit.land/api/v2/tiles/routes/tiles/{12/{2253}/{1204}.pbf?apikey=XXX&onestop_id=r-u6sce-69'

Unfortunately, this gives me the same invalid tile coordinates error. I removed the onestop_id from the endpoint, but this does not make a difference.

I have only basic knowledge about API endpoints and JSON queueries, so my apologies for the inconvenience if I am doing something wrong. Could you provide me with an example endpoint if possible?

**Comment by drewda** [comment]
Try your URL without curly brackets (which are just an indication of where to put the tile coordinates) and without the onestop_id query parameter (since the vector tiles cannot accept query parameters):

`https://transit.land/api/v2/tiles/routes/tiles/12/2253/1204.pbf?apikey=XXX`

For more information on how to use these MVT vector tiles, see the docs at https://www.transit.land/documentation/vector-tiles and try the example at https://www.transit.land/examples/example-map.html?apikey=xxx

Note that you do need to use a web map library capable of parsing MVT vector tiles, such as Mapbox GL JS or [Maplibre GL JS](https://github.com/maplibre/maplibre-gl-js).

This is not necessarily the easiest place to begin, so you may wish to wait for the v2 REST API to have JSON and GeoJSON to parse.

**Comment by GitBrum** [comment]
Thank you Drew! It works now.

One final question regarding the recommendation you gave; can you already indicate something about timeline of the completion of the v2 REST API? Based on this answer I will decide whether I look into parsing MVT vector tiles for my research or wait for the GeoJSON format. Thanks in advance!

**Comment by drewda** [comment]
Great!

We don't announce release dates in advance, but you are welcome to email info@interline.io and we will add you to the list of people to notify upon release.
