### ISSUE TITLE
Support ftp

### ISSUE THREAD

**Issue by davidchiles** [transitland/transitland#34]
Submitting feeds does not work for ftp addresses.

ftp://ftp.ci.santa-rosa.ca.us/SantaRosaCityBus/google_transit.zip

**Comment by drewda** [comment]
Thanks for the suggestion, @davidchiles!

Have you seen any other examples of GTFS feeds hosted on FTP servers?

**Comment by davidchiles** [comment]
@drewda Yeah it's definitely not the norm. I'll post any others here.

**Comment by davidchiles** [comment]
Found some more
```
ftp://metrostlouis.org/Transit/google_transit.zip
ftp://gisftp.metc.state.mn.us/google_transit.zip
```

**Comment by burritojustice** [comment]
ftp://gtfs.mot.gov.il/israel-public-transportation.zip (is up to date. 932.9 MB)

**Comment by stevevance** [comment]
More FTP-hosted feeds:

- [Artxanda Funicular, Spain](ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/FunicularArtxanda/google_transit.zip)
- [Bilbao, Spain](ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/MetroBilbao/google_transit.zip)

**Comment by arseny92** [comment]
> ftp://gtfs.mot.gov.il/israel-public-transportation.zip (is up to date. 932.9 MB)

and is updated **daily** at about 8:30pm UTC, official government feed, aggregates data from all local public transit companies as required by the Ministry

official info page (Hebrew): http://he.mot.gov.il/index.php?option=com_content&view=article&id=2244:pub-trn-gtfs&catid=167:pub-trn-dev-info&Itemid=304 (p.s.: the [faq page](http://media.mot.gov.il/PDF/HE_TRAFFIC_PUBLIC/GTFS.pdf) (Hebrew) references the old gtfs-data-exchange site)

Israel also side-by-side with the GTFS also provides SIRI information upon request (official page in Hebrew at http://he.mot.gov.il/index.php?option=com_content&view=article&id=2243:pub-trn-memchakim&catid=167:pub-trn-dev-info&Itemid=304 ) which is Service Interface for Real time Information. Both Stop Monitoring (SM) and vehicle monitoring (VM) are available, although VM is only for the transit operators themselves. Transitland would be even more useful if together with the bus stops from GTFS, it'd pull next-bus information for each stop live with SIRI SM.

**Comment by drewda** [comment]
@stevevance Thanks to @irees, the Datastore can now fetch from FTP. So please go ahead and add any of these FTP-based feeds that are still relevant.

**Comment by arseny92** [comment]
@drewda How come the above Israel feed still can't be added? The page says that the transit operator rejected the request with a 550 Access Denied. The feed is freely downloadable from the browser though, so shouldn't be an access problem

**Comment by stevevance** [comment]
@davidchiles The Santa Rosa [CityBus](https://transit.land/feed-registry/operators/o-9qbdx-santarosacitybus) is now in Transitland.

@arseny92 I'll get this figured out.

**Comment by drewda** [comment]
Closing this issue, since we've been able to successfully add the majority of the feeds mentioned here. If new problems come up, we can open a new issue.
