### ISSUE TITLE
NSW (Sydney) Australia Feed

### ISSUE THREAD

**Issue by deviousgeek** [transitland/transitland#38]
This feeds  [license](https://tdx.transportnsw.info/terms-conditions.php) allows us to use it, but it is behind HTTP Basic Auth, so it can't be submitted online.

The URL to the feed is here: https://tdx.transportnsw.info/download/files/full_greater_sydney_gtfs_static.zip

I have free to use account details if you would like, I think they require you to sign up mostly for statistical reasons, and to block you off if you make too many requests.

**Comment by deviousgeek** [comment]
I have redistributed the feed (also allowed) here for your inspection:
http://deviousgeek.com/stuff/full_greater_sydney_gtf_static.zip

**Comment by stevevance** [comment]
The Sydney feed has been moved (TDX was shut down), but [the new data portal](https://opendata.transport.nsw.gov.au/dataset/timetables-complete-gtfs) still requires an account.

**Comment by drewda** [comment]
This feed is now available without authentication, and is being added to Transitland: https://transit.land/dispatcher/changesets/6045

**Comment by stevevance** [comment]
The [feed](https://transit.land/dispatcher/feeds/f-r6-nswtrainlink~sydneytrains~buswayswesternsydney~interlinebus) is now enqueued to be imported!

**Comment by deviousgeek** [comment]
Excellent! Always great to see the govt. improving their data feeds and APIs. :)
