### ISSUE TITLE
Docker rig for entire Transitland stack (for local development)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#4]
related:

- transitland/playground#121
- transitland/feed-registry#79
- transitland/dispatcher#1

TODO:

- [ ] @sleepylemur  improve development experience on Mac (watching for file changes) https://github.com/mapzen/operations-engineering/issues/67
- [ ]  @hanbyul-here  fix URLs in nav bar links
- [ ]  @hanbyul-here  use shared stylesheets if/when it's time to do a style guide for transit.land

**Comment by drewda** [comment]
@baldur, @sleepylemur, @hanbyul-here I'm tagging you all on the various items we've discussed on and off over the past few weeks, but you all can set the pace. Switching to Docker isn't necessary for any of the releases we're working on for Transitland right now.

**Comment by baldur** [comment]
@sleepylemur can you install that new tool with @hanbyul-here and document
any parts that might be challenging so we have it recorded.

On Wed, Jan 27, 2016 at 2:39 PM, Drew Dara-Abrams <notifications@github.com>
wrote:

> @baldur <https://github.com/baldur>, @sleepylemur
> <https://github.com/sleepylemur>, @hanbyul-here
> <https://github.com/hanbyul-here> I'm tagging you all on the various
> items we've discussed on and off over the past few weeks, but you all can
> set the pace. Switching to Docker isn't necessary for any of the releases
> we're working on for Transitland right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transitland/transitland/issues/4#issuecomment-175816489>
> .
>



-- 
Baldur Gudbjornsson
VP Engineering
Mapzen - 347 268 1815

**Comment by sleepylemur** [comment]
good idea. dinghy looks very promising, we'll see if it passes the infamous "hanbyul's computer" test

**Comment by baldur** [comment]
@drewda we'll charge ahead with the mapzen.com first as that is more pressing. You should benefit from it. Closing this ticket ... feel free to reopen and assign to you if you want to monitor the mapzen.com process
