### ISSUE TITLE
Space Coast Area Transit

### ISSUE THREAD

**Issue by irees** [transitland/transitland#43]
Issue with RSPs.

on production: https://transit.land/dispatcher/feeds/f-djn-spacecoast~fl~us

To debug locally: `rails runner app/workers/feed_info_worker.rb http://data.trilliumtransit.com/gtfs/spacecoast-fl-us/spacecoast-fl-us.zip`

**Comment by doublestranded** [comment]
After some digging I discovered the root cause of this to be lack of support or filtering of trips without stop times. RSPs were not being generated for these trips, but the GTFSGraph still expected created RSPs in its trip -> RSP hash.

We should skip these trips for now within GTFSGraph.
