### ISSUE TITLE
Error submitting feed for Big Blue Bus

### ISSUE THREAD

**Issue by thekaveman** [transitland/transitland#45]
Trying to [submit a new feed](https://transit.land/feed-registry/feeds/new), getting the following error message:

![image](https://cloud.githubusercontent.com/assets/1783439/14123966/e33ceab0-f5b7-11e5-9c89-cb574e35c4ca.png)

For this GTFS feed: [`http://gtfs.bigbluebus.com/current.zip`](http://gtfs.bigbluebus.com/current.zip)

/cc @kevinsmgov

**Comment by irees** [comment]
Hi @thekaveman 

Thanks for your issue. We're looking into it, and will update this issue when it's resolved.

**Comment by kevinsmgov** [comment]
Hi @irees,  

We're not seeing any errors on our feed at this time. Also, the error message appears immediately on submission (doesn't look like it has a chance to run a feed validation process). Can you provide more information from the service that is getting the uploaded file?

![image](https://cloud.githubusercontent.com/assets/5798763/14125935/ad988d78-f5c2-11e5-8435-cef55a9b7a14.png)

**Comment by irees** [comment]
Hi @kevinsmgov and @thekaveman,

The issue has been resolved and the Big Blue Bus feed can now be submitted through the Feed Registry, if you would like to try again. If there is still an error, please re-open the issue.

Thank you again for your contribution and the error report.
