### ISSUE TITLE
'Error with submission' for RIPTA

### ISSUE THREAD

**Issue by davidchiles** [transitland/transitland#46]
Error trying to submit http://www.ripta.com/googledata/current/google_transit.zip. 
Do know what I'm doing wrong. Evertime I go back to the beginning of filling out the transit info it adds another entry.
![screen shot 2016-03-31 at 11 13 22 am](https://cloud.githubusercontent.com/assets/309772/14186120/9d3eb2de-f731-11e5-8bd4-a3fc30defcd4.png)

**Comment by davidchiles** [comment]
Same issue with NFTA with http://www.nfta.com/metro/__googletransit/google_transit.zip

**Comment by irees** [comment]
Hi @davidchiles 

Thanks again for your submissions and issue report. We've identified the issue (https://github.com/transitland/feed-registry/issues/306) and are working to resolve it now.

**Comment by irees** [comment]
@davidchiles We've fixed the issue, and it will be included in the next production deploy. Thanks again!
