### ISSUE TITLE
Multiple country entries for France

### ISSUE THREAD

**Issue by davidchiles** [transitland/transitland#47]
![screen shot 2016-04-19 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/309772/14656159/c7ce805c-063a-11e6-914a-1f01c0e873f9.png)

Only one has `State or Province` entries.

**Comment by drewda** [comment]
Thanks for noticing this, @davidchiles We'll investigate. Probably time to fetch updated listings from [Who's on First](https://whosonfirst.mapzen.com/) to put into the Transitland Feed Registry.
