### ISSUE TITLE
Error submitting feed Kobe subway

### ISSUE THREAD

**Issue by hkwi** [transitland/transitland#48]
I tried to submit http://codeforkobe.github.io/kobe-transit/kobe_subway_gtfs.zip, but getting "Error with submission" dialog message.

I'm sure the gtfs file passes the [validator](https://github.com/google/transitfeed).

Request
```
{"changeset":{"notes":"Changed submitted from Feed Registry for feed at http://codeforkobe.github.io/kobe-transit/kobe_subway_gtfs.zip","applied":false,"applied_at":null,"created_at":null,"updated_at":null,"payload":{"changes":[{"action":"createUpdate","operator":{"onestopId":"o-xn0j-","name":"City of Kobe","country":"Japan","state":"Hyōgo","metro":"Kobe","website":"http://www.city.kobe.lg.jp/life/access/transport/subway/","timezone":"Asia/Tokyo","geometry":{"type":"Polygon","coordinates":[[[135.15,34.65209999999998],[135.05699999999996,34.68149999999999],[135.04099999999997,34.687899999999985],[135.03,34.69939999999998],[135.017,34.719499999999975],[135.171344,34.76183100000001],[135.196,34.706700000000005],[135.196,34.69159999999999],[135.175,34.65689999999998],[135.165,34.654599999999995],[135.15,34.65209999999998]]]},"tags":{"agency_phone":"078-322-5958","agency_lang":"ja","agency_fare_url":null,"agency_id":null}}},{"action":"createUpdate","feed":{"onestopId":"f-xn0j-","geometry":{"type":"Polygon","coordinates":[[[135.017,34.6521],[135.196,34.6521],[135.196,34.761831],[135.017,34.761831],[135.017,34.6521]]]},"tags":{},"url":"http://codeforkobe.github.io/kobe-transit/kobe_subway_gtfs.zip","licenseName":"Creative Commons 3.0","licenseUrl":"http://creativecommons.org/licenses/by-sa/3.0/","licenseUseWithoutAttribution":"no","licenseAttributionText":"(C) Code for Kobe","licenseCreateDerivedProduct":"yes","licenseRedistribute":"yes","includesOperators":[{"gtfsAgencyId":null,"operatorOnestopId":"o-xn0j-"}]}}]},"user":{"email":"hiroaki.kawai@gmail.com","name":"Hiroaki KAWAI","affiliation":null,"user_type":"community_builder"}}}
```

Response
```
400 Bad Request

{"message":"Validation failed: Change payloads is invalid"}
```

**Comment by drewda** [comment]
Thanks for reporting this error, @hkwi. All of the detail is very helpful.

For some reason, the Onestop IDs generated for the operator and feed do not contain a name component. They should look more like `o-xn0j-kobe` and `f-xn0j-kobe`.

Did you include a name for the operator when filling out the "add a feed" forms?

In any case, we can manually fix this and create the changeset. Or if you'd like, you're welcome to do so yourself and POST it to `https://transit.land/api/v1/changesets` (as described in the docs at https://transit.land/documentation/datastore/api-endpoints.html )

Please let us know your preference, and thanks again for your contribution.

**Comment by hkwi** [comment]
GTFS agency.txt was created in Japanese (non ascii). Add feed form looked ascii was suitable, so I replaced the agency name in English version.

I manually fixed the `onestopId` as you suggested, and POST ed the data. The respose was following:

```
{"applied": false, "routes_destroyed": [], "applied_at": null, "imported_from_feed_onestop_id": null, "imported_from_feed_version_sha1": null, "change_payloads": [30111], "created_at": "2016-04-23T00:01:44.909Z", "operators_destroyed": [], "updated_at": "2016-04-23T00:01:44.909Z", "id": 1175, "user": 65, "operators_created_or_updated": [], "stops_destroyed": [], "stops_created_or_updated": [], "feeds_destroyed": [], "notes": "Changed submitted from Feed Registry for feed at http://codeforkobe.github.io/kobe-transit/kobe_subway_gtfs.zip", "feeds_created_or_updated": [], "routes_created_or_updated": []}
```

**Comment by drewda** [comment]
@hkwi: Glad to hear it worked manually. We'll apply the changeset and start importing the feed.

All of our libraries should be able to handle Unicode, not just ASCII, text. But we'll have a look. (cc @irees re the Ruby GTFS wrapper library supporting Unicode in `agency.txt`?)

For reference, the changeset created is now at https://transit.land/dispatcher/changesets/1175

**Comment by hkwi** [comment]
There looks some trouble in https://transit.land/dispatcher/feeds/f-xn0j-kobe . Anything I can do for it?

**Comment by doublestranded** [comment]
Hi @hkwi! Thank you again for your submission and for your patience! I am now investigating the problem and the possibilities for what can be done.

**Comment by doublestranded** [comment]
@hkwi Sorry for the long delay - the Kobe feed was successfully imported (including routes and schedule). The onestop id name components are now available in Japanese.
