### ISSUE TITLE
f-9q8v-commuteorgshuttle: nChangeset::Error Validation failed: Onestop invalid geometry hash

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#49]
https://transit.land/dispatcher/feeds/f-9q8v-commuteorgshuttle

>
{:exception_log=>"\nChangeset::Error Validation failed: Onestop invalid geometry hash\n[\"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/validations.rb:79:in `raise_record_invalid'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/validations.rb:43:in `save!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:29:in `save!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:291:in `block in save!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:291:in `save!'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:73:in `block in create_making_history'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:67:in `create_making_history'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:39:in `block in apply_changes_create_update'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:33:in `each'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:33:in `apply_changes_create_update'\", \"/srv/www/transitland/releases/20160422191542/app/models/concerns/current_tracked_by_changeset.rb:24:in `apply_changes'\", \"/srv/www/transitland/releases/20160422191542/app/models/change_payload.rb:73:in `block in apply!'\", \"/srv/www/transitland/releases/20160422191542/app/models/change_payload.rb:70:in `<<'\", \"/srv/www/transitland/releases/20160422191542/app/models/change_payload.rb:70:in `each'\", \"/srv/www/transitland/releases/20160422191542/app/models/change_payload.rb:70:in `each'\", \"/srv/www/transitland/releases/20160422191542/app/models/change_payload.rb:70:in `apply!'\", \"/srv/www/transitland/releases/20160422191542/app/models/changeset.rb:162:in `block (2 levels) in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/srv/www/transitland/releases/20160422191542/app/models/changeset.rb:161:in `block in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'\", \"/srv/www/transitland/releases/20160422191542/app/models/changeset.rb:159:in `apply!'\", \"/srv/www/transitland/releases/20160422191542/app/services/gtfs_graph.rb:87:in `create_change_osr'\", \"/srv/www/transitland/releases/20160422191542/app/workers/feed_eater_worker.rb:46:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'\"]\n"}

**Comment by doublestranded** [comment]
resolved by https://github.com/transitland/transitland-datastore/issues/575
