### ISSUE TITLE
Boston Ferry has route geometries terminating in water

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland#53]
![pasted image at 2016_05_13 12_59 pm](https://cloud.githubusercontent.com/assets/3828027/15256650/52bca0a8-18f7-11e6-8e7a-4cb785e697ae.png)

**Comment by stevevance** [comment]
Shouldn't a ferry's route terminate in water?

**Comment by drewda** [comment]
Closing this, since @gknisely resolved the issue by making OSM edits.
