### ISSUE TITLE
Transfort import fails with ArgumentError at app/models/operator.rb:139

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#54]
https://transit.land/dispatcher/feeds/f-9xj-transfortcityoffortcollins

https://app.getsentry.com/mapzen/datastore-prod/issues/130359976/

> {:exception_log=>"\ninvalid byte sequence in UTF-8\n[\"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/blank.rb:117:in `==='\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/blank.rb:117:in`blank?'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/blank.rb:24:in `present?'\", \"/srv/www/transitland/releases/20160524185737/app/models/operator.rb:139:in`select'\", \"/srv/www/transitland/releases/20160524185737/app/models/operator.rb:139:in `from_gtfs'\", \"/srv/www/transitland/releases/20160524185737/app/services/gtfs_graph.rb:238:in`block in load_tl_operators'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in`each'\", \"/srv/www/transitland/releases/20160524185737/app/services/gtfs_graph.rb:228:in `load_tl_operators'\", \"/srv/www/transitland/releases/20160524185737/app/services/gtfs_graph.rb:36:in`create_change_osr'\", \"/srv/www/transitland/releases/20160524185737/app/workers/feed_eater_worker.rb:46:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in`execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:128:in`block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in`synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in`call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in`call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in`call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in`block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in`call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in`call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in`block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in`process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in`run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in`block in safe_thread'\"]\n"}

**Comment by doublestranded** [comment]
A quick investigation reveals this is probably the result of Windows-1252 encoding.

**Comment by drewda** [comment]
Good to know, @doublestranded Let's see if the agency can use UTF-8 encoding (since that is a GTFS spec requirement). Perhaps @tyleragreen knows who to ask?

If not, we'll eventually have to add some amount of feed pre-processing to handle this and other feed quirks.

**Comment by tyleragreen** [comment]
I sent out an email to see if I can find the source. Hope to let you know soon!

**Comment by drewda** [comment]
Thanks, @tyleragreen!

**Comment by tyleragreen** [comment]
The contact for the Transfort GTFS feed is Bridget Ronayne at bronayne@fcgov.com, if you want to reach out to her!

**Comment by drewda** [comment]
More recent imports have succeeded!
