### ISSUE TITLE
Boston Harbor Islands Ferry / InterIsland route has trip with only two repeated stops

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland#55]
Route Stop Pattern: r-drt8d-interislandferry-96c6ee-df1b03
GTFS trips: 
NPS_BOHA_SU15-Wd__I2__1115_IS
NPS_BOHA_SU15-We__I2__1115_IS

This is valid GTFS, but the associated trip shape indicates this might be a mistake.
Transitland might have to filter out and/or tag as issues these cases in the future. 

[onestopId is f-drt8-nps~boha~ferries](https://transit.land/feed-registry/operators/o-drt8-bostonharborislandsnationalandstatepark)

**Comment by stevevance** [comment]
Is this still a problem?

**Comment by doublestranded** [comment]
Not sure - this route is missing from the latest imported feed:
https://transit.land/api/v1/routes/r-drt8d-interislandferry (shows up with empty RouteStopPatterns).
There may be other, similar routes in the feed with this same issue so I'll check to be sure.
