### ISSUE TITLE
Berlin feed import errors

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#56]
Reported on Twitter:
- https://twitter.com/rynbtmn/status/741196177157332992
- https://twitter.com/rynbtmn/status/741196310154465280

the ZIP file: http://www.vbb.de/de/datei/GTFS_VBB_EndeApr_Dez2016.zip

metadata: http://daten.berlin.de/datensaetze/vbb-fahrplandaten-ende-april-bis-dezember-2016

**Comment by batje** [comment]
More so, the VBB does not update 1 GTFS file, but publishes a new one about every month. Latest at time of this comment: http://www.vbb.de/de/datei/GTFS_VBB_EndeJul_Dez2016.zip Also corrupt according to the upload form.

**Comment by aardila** [comment]
It's not corrupt as I would understand a "(zip) file being corrupt". It's just not GTFS compliant in that the zip contains two other GTFS zips, one with shapefiless and and the other without (`GTFS_VBB_Dez2016 Dez2017_mit_shape_files.zip` and `GTFS_VBB_Dez2016 Dez2017_ohne_shape_files.zip` respectively as of the [last version](http://daten.berlin.de/datensaetze/vbb-fahrplandaten-dezember-2016-bis-dezember-2017)).

[Issue in Valhalla](https://github.com/valhalla/valhalla/issues/12) for cross-referencing

**Comment by aardila** [comment]
There is a newer version of the feed published by VBB under http://www.vbb.de/de/datei/GTFS_VBB_Dez2016_Dez2017.zip. That seems to be for a 12-month period, but has introduced the problem that the zip is not GTFS compliant in that it acts as a container for two GTFS zip files, one with shapefiles and the other without (`GTFS_VBB_Dez2016 Dez2017_mit_shape_files.zip` and `GTFS_VBB_Dez2016 Dez2017_ohne_shape_files.zip` respectively).

**Comment by drewda** [comment]
the feed and its operators have been successfully added to Transitland: https://transit.land/dispatcher/feeds/f-u3-g%C3%BCnterangerg%C3%BCterverkehrsgmbh~coomnibusvermietungkg~fritzbeh

errors on import:
> {:exception_log=>"\nundefined method `factory' for nil:NilClass\n[\"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/rgeo-0.5.3/lib/rgeo/feature/types.rb:163:in `cast'\", \"/www/transitland/releases/20170113201518/app/models/concerns/has_a_geographic_geometry.rb:63:in `geometry'\", \"/www/transitland/releases/20170113201518/app/models/concerns/has_a_geographic_geometry.rb:20:in `block in convex_hull'\", \"/www/transitland/releases/20170113201518/app/models/concerns/has_a_geographic_geometry.rb:20:in `map'\", \"/www/transitland/releases/20170113201518/app/models/concerns/has_a_geographic_geometry.rb:20:in `convex_hull'\", \"/www/transitland/releases/20170113201518/app/services/gtfs_graph.rb:408:in `block in load_tl_operators'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'\", \"/www/transitland/releases/20170113201518/app/services/gtfs_graph.rb:389:in `load_tl_operators'\", \"/www/transitland/releases/20170113201518/app/services/gtfs_graph.rb:91:in `create_change_osr'\", \"/www/transitland/releases/20170113201518/app/workers/feed_eater_worker.rb:30:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]\n"}

**Comment by irees** [comment]
Hi @aardila

We are testing a fix now. I'll report back if it fixes the issue. https://github.com/transitland/transitland-datastore/pull/966/files

**Comment by drewda** [comment]
Another fix necessary for Berlin import: https://github.com/transitland/transitland-datastore/issues/972

**Comment by irees** [comment]
Berlin is now imported on production.

https://transit.land/dispatcher/feeds/f-u3-g%C3%BCnterangerg%C3%BCterverkehrsgmbh~coomnibusvermietungkg~fritzbeh

**Comment by aardila** [comment]
Glad to hear the issues with the feed could be ironed out! Just wondering if there were plans to process the new feed I linked in my previous comment? The feed you linked to @irees expired in 2016 if I'm understanding this correctly _Latest calendar date: Fri Dec 09 2016 19:00:00 GMT-0500 (EST)_. Not sure the time zone is correct, but data at the "Fetched from URL" is definitely for the old feed (VBB doesn't update the same URL with the latest data, unfortunately).

**Comment by drewda** [comment]
@stevevance can you update the URL and tag this as a feed with an unstable URL?

**Comment by stevevance** [comment]
It took some troubleshooting from @irees, because of the way the ZIP file structure has sub-zip files, and that the server has an HTML redirect, but he found that the correct URL is `http://www.vbb.de/de/download/GTFS_VBB_Dez2016_Dez2017.zip#GTFS_VBB_Dez2016%20Dez2017_mit_shape_files.zip`.

**Comment by aardila** [comment]
FYI, just noticed that there was an [updated version published on January 23](https://daten.berlin.de/datensaetze/vbb-fahrplandaten-januar-2017-bis-dezember-2017), which removes the (terrible, horrible, very bad, no good) nested zip file structure. The link to the zip file is http://www.vbb.de/de/datei/GTFS_VBB_Jan_Dez2017.zip but that seems to redirect to www.vbb.de/de/download/GTFS_VBB_Jan_Dez2017.zip
