### ISSUE TITLE
Seattle area transit operators and feeds

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#57]
>
We noticed that you have a listing for Seattle that is only partial but not sure how we can correct it optimally – You have Sound Transit listed but a link to King County Metro’s GTFS. There are about 9 different agencies serving the greater Seattle area, this is only one of them. Sound Transit serves as the regional data consolidator for API access through what was originally One Bus Away. We publish the individual agency GTFS here: http://www.soundtransit.org/Developer-resources/Data-downloads but there is not one single url for all (except for our beta version). If you are only having one listing for the area that page is more accurate than just one link, if your preference is to have the current GTFS url than the agency info should be modified to be King County Metro. Let me know if I can provide additional information.

//cc @rmglennon

**Comment by stevevance** [comment]
I am working through all 9 of these today and they will be done today.

**Comment by stevevance** [comment]
There's overlap in feeds and operators for *Pierce Transit* and *Sound Transit*. 

The feed that contains Pierce Transit also contains Sound Transit buses. 
The Sound Transit feed that is already in the Feed Registry contains only Sound Transit commuter and light rail. 

The Sound Transit operator needs to be linked to the Pierce Transit feed and the existing Sound Transit feed. The geohash in the `onestopId` string may need to be updated to encompass the geographic area for the ST buses, commuter rail, and light rail.

**Comment by stevevance** [comment]
There's a corrupt ZIP file for *JBLM GO Transit*. When you [download the feed](http://developer.onebusaway.org/tmp/sound/gtfs/modified/99_gtfs.zip) you get a ZIP file that unzips to a gzip and it just keeps unzipping further and further. 

@irees and @drewda Can you take a look? There's no changeset for it because it can't be read by the server.

**Comment by drewda** [comment]
@stevevance sounds like a problem best handled on the data producer side.

@rmglennon can you mention this problem about zip files to the original requestor on the support ticket?

We can always just leave this one off the list for now and mention at State of the Map that it's an open item we could use help with from the data producer.

**Comment by rmglennon** [comment]
I tried to open the JBLM GO zip (based on some troubleshooting tips I found), but could not get it working either. I've sent a note to the support ticket contact at Sound Transit.

**Comment by stevevance** [comment]
I've added all of the Seattle-area feeds. We now have 7 operators if you search for "Seattle", and 20 operators if you search for "Washington" (state). The list provided by the person who submitted the support ticket was helpful to gathering all of the feeds. 

## Remaining issues
- I couldn't add *JBLM GO Transit*, which is an operator on a military base near Tacoma. 
- Sound Transit has 28 bus routes, which are scattered among several feeds. I can't account for all of them yet.
