### ISSUE TITLE
Long Beach Transit - problem when adding to feed registry

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#61]
Long Beach Transit sent us this GTFS file for June 2016. The URL cannot be parsed in step 1 of the add a feed flow. 

https://lbtransit.box.com/shared/static/can2nrqj09td9n047jsrfq14y800u9zt.zip

![image](https://cloud.githubusercontent.com/assets/4380498/16213465/7343d29e-3704-11e6-830d-d0e11fc04106.png)

**Comment by drewda** [comment]
No longer an issue with newer versions of the Long Beach feed.

Submitted in changeset https://transit.land/dispatcher/changesets/1967

Now available in Feed Registry: https://transit.land/feed-registry/operators/o-9q5b-longbeachtransit
