### ISSUE TITLE
BC Transit

### ISSUE THREAD

**Issue by irees** [transitland/transitland#62]
BC Transit previously consolidated all operators into a single feed. Recently, they moved each operator to a separate GTFS Feed.

John and I resolved the situation by creating a new Feed Registry submission for each new GTFS url. I then consolidated these Feeds into a single changeset, and edited `includesOperators` to point to the existing Operators.

**Comment by drewda** [comment]
@irees can include links to the changesets on this ticket for future reference and also delete any unapplied changesets that remain?

**Comment by irees** [comment]
Create new feeds and associate with existing operators:
https://transit.land/dispatcher/changesets/1787

Delete old feed:
https://transit.land/dispatcher/changesets/1788

Updated feeds:
https://transit.land/feed-registry/?state=British%20Columbia

**Comment by drewda** [comment]
@irees sounds complete. Ready to close?

**Comment by irees** [comment]
Issue during import -- looking into it
https://transit.land/dispatcher/feeds/f-c2bt-bctransit~whistlertransitsystem

**Comment by drewda** [comment]
Related: https://github.com/transitland/transitland-datastore/issues/687

**Comment by drewda** [comment]
@irees is going double check for any duplicate stops/routes/etc.

**Comment by irees** [comment]
Old Stops and Routes removed via changeset:
https://transit.land/dispatcher/changesets/2135

Old RSPs deleted manually (issue with changeset, see https://github.com/transitland/transitland-datastore/issues/684)
