### ISSUE TITLE
"Region" on the Feed Registry should be "Metro"

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#67]
In some parts of the world, "region" has an official meaning and it doesn't mean a metropolitan city. For example, a region in Italy is greater than a province, which is greater than a city. 

Essentially, "metro" has the same meaning in all parts of the world, but region doesn't. 

The JSON payload in the change sets asks for "metro", and we've been using city areas, but the website says "region". 

Some of the feeds are for intercity coach buses, and they serve multiple metro areas, but single regions. 

Proposal: Change "region" text on the Feed Registry table heading to "metro".

**Comment by drewda** [comment]
@stevevance thanks for identifying the inconsistencies. Yes, it does sound better to standardize on "metro" in both the Datastore API and Feed Registry front-end. We'll handle this under: https://github.com/transitland/feed-registry/issues/356

Note that the "add a feed" flow and documentation do suggest that users use location of the headquarters for an operator if it's unclear how to describe its entire coverage area, or if it cuts across many places.
