### ISSUE TITLE
f-9q8v-commuteorgshuttle: Feed moved

### ISSUE THREAD

**Issue by irees** [transitland/transitland#72]
f-9q8v-commuteorgshuttle
Server exception, not a zip file: http://www.commute.org/files/gtfs/Masterzip_4.1.16.zip

**Comment by drewda** [comment]
I'll follow up with our contact at that agency.

**Comment by drewda** [comment]
E-mailed the shuttle manager at Peninsula Traffic Congestion Relief Alliance.

**Comment by drewda** [comment]
Just got the updated URL from him, and I updated it in Datastore: https://transit.land/dispatcher/changesets/2104
