### ISSUE TITLE
Error importing  f-sqc2-amatpalermospa: `No agencies found that match operators_in_feed`

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#78]
https://transit.land/dispatcher/feeds/f-sqc2-amatpalermospa
>
{:exception_log=>"\nNo agencies found that match operators_in_feed\n[\"/srv/www/transitland/releases/20160727190729/app/services/gtfs_graph.rb:38:in `create_change_osr'\", \"/srv/www/transitland/releases/20160727190729/app/workers/feed_eater_worker.rb:47:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]\n"}

**Comment by irees** [comment]
Updated OperatorsInFeed:
https://transit.land/dispatcher/changesets/2150

**Comment by irees** [comment]
Updates to new feed, removed old feed
https://transit.land/dispatcher/changesets/2152
