### ISSUE TITLE
Amtrak route geometries

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland#79]
Amtrak Sunset Limited starts in Orlando instead of New Orleans.

Once Issues are on prod.

**Comment by drewda** [comment]
@irees since we recently reimported the Amtrak feed, can you check to see that your edit of the Sunset Limited geometry has remained? Assuming "sticky attributes" worked on the route geometry column, it's fine and we can close this issue.

**Comment by irees** [comment]
It might have been cleared out by a run of the unreferenced entities script - I restored it from OldRouteStopPattern via a changeset.

https://transit.land/dispatcher/changesets/4969
