### ISSUE TITLE
Support multiple countries, states, and metros

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#82]
Some feeds span multiple countries. 

Adjust the JSON payload model to accept an array of country names. For the Feed Registry and Playground this would have to be expanded. I don't know the consequences for the datastore and API.

````
"operator": {
                "onestopId": "o-gc-firstgreatwestern",
                "name": "First Great Western",
                "country": ["England", "Wales"],
                "website": "http://www.firstgreatwestern.co.uk/",
                "timezone": "Europe/London"
}
````

With some feeds I've been using a comma-separated list of metro names.

**Comment by drewda** [comment]
Currently the Feed Registry, Playground, and some other consumers of the API assume that only one of each (country/state/metro) is given per operator. This type of "drill-down" by location may not be a full and complete description of larger operators' service areas--but it's still possible to search and visualize the coverage areas of larger operators by doing bounding box or radius queries.

For now, let's continue to just specify one level of locality for each operator. If necessary, for operators with very large coverage areas that slop of borders, let's just specify the locality as the headquarters of the operator.

In the future, an option to consider will be tighter integration with the Who's on First hierarchy. Related to https://github.com/transitland/transitland-datastore/issues/312
