### ISSUE TITLE
Handmade feed for City of Carlsbad, NM

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#86]
http://cityofcarlsbadnm.com/transit.cfm

The City of Carlsbad, New Mexico has a small public transit system with 5,000 riders per month through on-demand dial-a-ride, fixed routes, and paratransit. It does not publish a feed for its fixed routes, and so we received a submission for a handmade feed hosted on GitHub. 

"The stops were surveyed by me in a descriptive manner and then placed spatially based on downloading OSM data in JOSM (e.g. stop is right at intersection of Street 1 and 2). There is currently no paths.txt file in the feed, but I believe I have a shapes.txt file offline with paths derived wholly from OSM data. Either way, I'm unsure if this falls under the purview of OSM's ODbL as a derivative work or if it's separated enough to count as my own work."

See changeset 2186 and support ticket 855.

**Comment by drewda** [comment]
Was added and imported.

See https://transit.land/dispatcher/changesets/2186 and https://transit.land/dispatcher/feeds/f-9tvbk-carlsbadmunicipaltransitsystem
