### ISSUE TITLE
adopt a code for conduct?

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#87]
From time to time, we've talked about adopting a code of conduct for the Transitland project. It's an open project that welcomes contributors from around the world, some of whom participate as part of their "day jobs," others trying to create a business off of Transitland data, and still others participating as a side project or hobby.  When things go well--and they most often do--it's a vibrant mix of people and interests. But there's also the possibility of misunderstandings, especially when people with different background and motivations are talking at each other through text boxes. A code of conduct (CoC) could help clarify "rules of the road" and remind all participants how to come to Transitland with the best of intentions.
- Is there an existing CoC template that's worth using?
- Any downsides to adopting a CoC to consider in advance?
- Where to post?
  - a `CONTRIBUTING.MD` in https://github.com/transitland/transitland
  - https://transit.land/participate/

//cc @rmglennon @meghanhade @dianashk @kathleenld @awright

Timeframe: The next few weeks, although not urgent.

**Comment by stevevance** [comment]
Can you give an example of a misunderstanding?
