### ISSUE TITLE
Script-made feed for Trenord (in Italy)

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#88]
Trenord, a rail operator in Lombardy, Italy, [publishes the files](https://www.dati.lombardia.it/browse?tags=trenord&utf8=✓) of a GTFS feed individually on a Socrata-powered portal. 

A contributor wrote a python script that [combines them into GTFS](https://github.com/openTrenord/script). 

See [changeset 2248](https://transit.land/dispatcher/changesets/2248). 

Per my plans to prioritize "simple" feeds to reduce the backlog of submissions, I haven't accepted it yet.

**Comment by Airon90** [comment]
This bug can be closed as Regione Lombardia now provides an [official GTFS file](https://www.dati.lombardia.it/Mobilit-e-trasporti/Orario-Ferroviario-Regionale-Gtfs/3z4k-mxz9) and an user already [edited the feed](https://transit.land/feed-registry/operators/o-u0n-trenord).

**Comment by stevevance** [comment]
@Airon90 Thanks for the update.
