### ISSUE TITLE
Bologna and Ferrara, Italy, bus feeds have versioned filenames

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#89]
The feeds for [Ferrara buses](https://solweb.tper.it/web/tools/open-data/open-data-detail.aspx?source=&filename=gommagtfsfe&version=20160617) and [Bologna buses](https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=solweb.tper.it&filename=gommagtfsbo&version=20160629&format=zip) have `version` parameters in their filenames, which are required to download the file. And they must have valid values (i.e. the `version` value must point to an actual snapshot of the data). (Click through those links to get to the actual ZIP file URL.)

Additionally, when you try to submit them to the feed registry, it throws the error that this doesn't appear to be a valid GTFS feed – and it doesn't, because it only has one file, `agency.txt`.

**Comment by Airon90** [comment]
There is even [another feed](https://solweb.tper.it/web/tools/open-data/open-data-detail.aspx?source=tper.it&filename=gommagtfsblq&version=20160901) similar to Ferrara and Bologna ones.

**Comment by stevevance** [comment]
@Airon90 That feed for the BLQ Aerobus (shuttle from the city center to the airport) is also invalid, because it only has the `agency.txt` file. 

I am closing this issue because no feed can be found.
