### ISSUE TITLE
SEPTA feed has nested zip files and changing URL

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#9]
https://github.com/septadev/GTFS/releases/download/v20160111.1/gtfs_public.zip

- includes nested zip files, will be resolved by https://github.com/transitland/transitland-datastore/issues/316
- also has a changing URL, for future consideration under #18

**Comment by msmollin** [comment]
+1 for this.

**Comment by drewda** [comment]
Old news but good news:

Now that transitland/transitland-datastore#316 is complete, we can now handle the nested ZIP files in SEPTA feeds. On production server at: https://transit.land/feed-registry/operators/o-dr4-septa

Support for unstable URLs is still pending, under #18

//cc @msmollin
