### ISSUE TITLE
f-u0j-gruppotorinesetrasporti~gttservizioextraurbano~gruppotorin: Changed feed

### ISSUE THREAD

**Issue by irees** [transitland/transitland#93]
https://transit.land/dispatcher/feeds/f-u0j-gruppotorinesetrasporti~gttservizioextraurbano~gruppotorin

The current feed appears to combine a few different feeds (Torino + SFM), which are now only available separately:

http://opendata.5t.torino.it/gtfs/

**Comment by drewda** [comment]
For @irees, @stevevance, and myself to chat about on our next call.

Similar to how BC Transit switched from a consolidated feed to disaggregated feeds: https://github.com/transitland/transitland/issues/62

**Comment by stevevance** [comment]
Four operators rely on the Torino feed

http://opendata.5t.torino.it/gtfs/torino_it.zip

- https://transit.land/feed-registry/operators/o-u0j2-gruppotorinesetrasporti
- https://transit.land/feed-registry/operators/o-u0j-gruppotorinesetrasporti
- https://transit.land/feed-registry/operators/o-u0j-gttservizioextraurbano
- https://transit.land/feed-registry/operators/o-u0j82-gttservizituristici

**Comment by stevevance** [comment]
@irees @drewda The [Cuneo feed](http://opendata.5t.torino.it/gtfs/cuneo_it.zip) cannot be submitted through feed registry; I get an "error with submission" JS alert.

**Comment by drewda** [comment]
@stevevance is adding the Cuneo feed still relevant?

**Comment by stevevance** [comment]
@drewda No, Cuneo operators are covered under [this feed](https://transit.land/dispatcher/feeds/f-u0j-piemonte~autobus).
