### ISSUE TITLE
f-dhw-miamidadetransit: fetch error "execution expired"

### ISSUE THREAD

**Issue by irees** [transitland/transitland#96]
https://transit.land/dispatcher/feeds/f-dhw-miamidadetransit

GTFS::Source.build(url) works ok locally - check full FeedFetcher job locally.

**Comment by irees** [comment]
Same error with f-9q5-ladot

https://transit.land/dispatcher/feeds/f-9q5-ladot

**Comment by drewda** [comment]
Both feeds have been fetching just fine recently.
